/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth from "../auth.js";
import type * as comments_api from "../comments/api.js";
import type * as competitions_access from "../competitions/access.js";
import type * as competitions_api from "../competitions/api.js";
import type * as competitions_nodeActions from "../competitions/nodeActions.js";
import type * as competitions_weekendOverrides from "../competitions/weekendOverrides.js";
import type * as core_admin from "../core/admin.js";
import type * as core_auth from "../core/auth.js";
import type * as core_labels from "../core/labels.js";
import type * as core_phases from "../core/phases.js";
import type * as core_seed from "../core/seed.js";
import type * as core_teams from "../core/teams.js";
import type * as core_userThemeSettings from "../core/userThemeSettings.js";
import type * as core_users from "../core/users.js";
import type * as core_views from "../core/views.js";
import type * as crons from "../crons.js";
import type * as discord_actions from "../discord/actions.js";
import type * as discord_api from "../discord/api.js";
import type * as discord_client from "../discord/client.js";
import type * as discord_commands from "../discord/commands.js";
import type * as discord_config from "../discord/config.js";
import type * as discord_handler from "../discord/handler.js";
import type * as discord_interactions from "../discord/interactions.js";
import type * as discord_rest from "../discord/rest.js";
import type * as discord_slashCommands from "../discord/slashCommands.js";
import type * as emailQueue_api from "../emailQueue/api.js";
import type * as emailQueue_counters from "../emailQueue/counters.js";
import type * as emailQueue_diagnostics from "../emailQueue/diagnostics.js";
import type * as emailQueue_enqueue from "../emailQueue/enqueue.js";
import type * as emailQueue_pool from "../emailQueue/pool.js";
import type * as emailQueue_types from "../emailQueue/types.js";
import type * as emailQueue_worker from "../emailQueue/worker.js";
import type * as emails_NotificationDigestEmail from "../emails/NotificationDigestEmail.js";
import type * as emails_NotificationEmail from "../emails/NotificationEmail.js";
import type * as emails_shared from "../emails/shared.js";
import type * as http from "../http.js";
import type * as integrations_canva_actions from "../integrations/canva/actions.js";
import type * as integrations_canva_client_client from "../integrations/canva/client/client.js";
import type * as integrations_canva_client_client_client_index from "../integrations/canva/client/client/client/index.js";
import type * as integrations_canva_index from "../integrations/canva/index.js";
import type * as integrations_canva_lib_helpers from "../integrations/canva/lib/helpers.js";
import type * as integrations_canva_sharing from "../integrations/canva/sharing.js";
import type * as integrations_google_client_sheetsClient from "../integrations/google/client/sheetsClient.js";
import type * as integrations_google_index from "../integrations/google/index.js";
import type * as integrations_google_sheets from "../integrations/google/sheets.js";
import type * as integrations_google_sheetsQueries from "../integrations/google/sheetsQueries.js";
import type * as integrations_linkedActions from "../integrations/linkedActions.js";
import type * as integrations_linkedActions_config from "../integrations/linkedActions/config.js";
import type * as integrations_linkedActions_permissions from "../integrations/linkedActions/permissions.js";
import type * as integrations_linkedActions_runners from "../integrations/linkedActions/runners.js";
import type * as integrations_linkedActions_shapes from "../integrations/linkedActions/shapes.js";
import type * as integrations_oauth_flow from "../integrations/oauth/flow.js";
import type * as integrations_oauth_index from "../integrations/oauth/index.js";
import type * as integrations_oauth_providers from "../integrations/oauth/providers.js";
import type * as integrations_services from "../integrations/services.js";
import type * as integrations_tokens from "../integrations/tokens.js";
import type * as integrations_tokens_runtime from "../integrations/tokens/runtime.js";
import type * as integrations_tokens_tokenDefinition from "../integrations/tokens/tokenDefinition.js";
import type * as integrations_tokens_types from "../integrations/tokens/types.js";
import type * as integrations_types from "../integrations/types.js";
import type * as integrations_wca_actions from "../integrations/wca/actions.js";
import type * as integrations_wca_client_client from "../integrations/wca/client/client.js";
import type * as integrations_wca_client_client_client_index from "../integrations/wca/client/client/client/index.js";
import type * as integrations_wca_index from "../integrations/wca/index.js";
import type * as integrations_wca_lib_registrations from "../integrations/wca/lib/registrations.js";
import type * as integrations_wca_schedule from "../integrations/wca/schedule.js";
import type * as integrations_wca_twoFactor from "../integrations/wca/twoFactor.js";
import type * as lib_avatarResolver from "../lib/avatarResolver.js";
import type * as lib_commentParentId from "../lib/commentParentId.js";
import type * as lib_constants from "../lib/constants.js";
import type * as lib_defaultAvatar from "../lib/defaultAvatar.js";
import type * as lib_deploymentGuard from "../lib/deploymentGuard.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_oauth from "../lib/oauth.js";
import type * as lib_permissions_authn from "../lib/permissions/authn.js";
import type * as lib_permissions_index from "../lib/permissions/index.js";
import type * as lib_permissions_policies from "../lib/permissions/policies.js";
import type * as lib_permissions_require from "../lib/permissions/require.js";
import type * as lib_permissions_resources from "../lib/permissions/resources.js";
import type * as lib_permissions_teams from "../lib/permissions/teams.js";
import type * as lib_refunds from "../lib/refunds.js";
import type * as lib_retry from "../lib/retry.js";
import type * as lib_sanitize from "../lib/sanitize.js";
import type * as lib_seedData from "../lib/seedData.js";
import type * as lib_siteUrls from "../lib/siteUrls.js";
import type * as lib_transforms from "../lib/transforms.js";
import type * as lib_types from "../lib/types.js";
import type * as lib_validators from "../lib/validators.js";
import type * as migrations_renameNotificationTypes from "../migrations/renameNotificationTypes.js";
import type * as notifications_api from "../notifications/api.js";
import type * as notifications_catalog from "../notifications/catalog.js";
import type * as notifications_discord_actions from "../notifications/discord/actions.js";
import type * as notifications_discord_context from "../notifications/discord/context.js";
import type * as notifications_discord_delivery from "../notifications/discord/delivery.js";
import type * as notifications_discord_message from "../notifications/discord/message.js";
import type * as notifications_discord_notifications_commentAdded from "../notifications/discord/notifications/commentAdded.js";
import type * as notifications_discord_notifications_commentReplied from "../notifications/discord/notifications/commentReplied.js";
import type * as notifications_discord_notifications_competitionPhaseChanged from "../notifications/discord/notifications/competitionPhaseChanged.js";
import type * as notifications_discord_notifications_dueDateApproaching from "../notifications/discord/notifications/dueDateApproaching.js";
import type * as notifications_discord_notifications_dueDateChanged from "../notifications/discord/notifications/dueDateChanged.js";
import type * as notifications_discord_notifications_dueDateOverdue from "../notifications/discord/notifications/dueDateOverdue.js";
import type * as notifications_discord_notifications_index from "../notifications/discord/notifications/index.js";
import type * as notifications_discord_notifications_progressUpdateAdded from "../notifications/discord/notifications/progressUpdateAdded.js";
import type * as notifications_discord_notifications_relationBlocked from "../notifications/discord/notifications/relationBlocked.js";
import type * as notifications_discord_notifications_relationUnblocked from "../notifications/discord/notifications/relationUnblocked.js";
import type * as notifications_discord_notifications_reminderTriggered from "../notifications/discord/notifications/reminderTriggered.js";
import type * as notifications_discord_notifications_taskApproved from "../notifications/discord/notifications/taskApproved.js";
import type * as notifications_discord_notifications_taskAssigned from "../notifications/discord/notifications/taskAssigned.js";
import type * as notifications_discord_notifications_taskAwaitingReview from "../notifications/discord/notifications/taskAwaitingReview.js";
import type * as notifications_discord_notifications_taskMentioned from "../notifications/discord/notifications/taskMentioned.js";
import type * as notifications_discord_notifications_taskPriorityChanged from "../notifications/discord/notifications/taskPriorityChanged.js";
import type * as notifications_discord_notifications_taskStatusChanged from "../notifications/discord/notifications/taskStatusChanged.js";
import type * as notifications_discord_notifications_taskUnapproved from "../notifications/discord/notifications/taskUnapproved.js";
import type * as notifications_discord_notifications_taskUnassigned from "../notifications/discord/notifications/taskUnassigned.js";
import type * as notifications_discord_registry from "../notifications/discord/registry.js";
import type * as notifications_discord_types from "../notifications/discord/types.js";
import type * as notifications_discord_utils from "../notifications/discord/utils.js";
import type * as notifications_emit from "../notifications/emit.js";
import type * as notifications_index from "../notifications/index.js";
import type * as notifications_internal from "../notifications/internal.js";
import type * as notifications_lib_cleanup from "../notifications/lib/cleanup.js";
import type * as notifications_lib_entities from "../notifications/lib/entities.js";
import type * as notifications_lib_notificationAccess from "../notifications/lib/notificationAccess.js";
import type * as notifications_lib_notificationBuilders from "../notifications/lib/notificationBuilders.js";
import type * as notifications_lib_notificationDueDates from "../notifications/lib/notificationDueDates.js";
import type * as notifications_lib_notificationTemplates from "../notifications/lib/notificationTemplates.js";
import type * as notifications_lib_notificationTypes from "../notifications/lib/notificationTypes.js";
import type * as notifications_lib_payload from "../notifications/lib/payload.js";
import type * as notifications_lib_recipientCollection from "../notifications/lib/recipientCollection.js";
import type * as notifications_lib_validators from "../notifications/lib/validators.js";
import type * as notifications_lib_watcherPolicy from "../notifications/lib/watcherPolicy.js";
import type * as notifications_lib_watcherRecipients from "../notifications/lib/watcherRecipients.js";
import type * as notifications_recipients_expand from "../notifications/recipients/expand.js";
import type * as notifications_subscriptions from "../notifications/subscriptions.js";
import type * as notifications_testNotifications from "../notifications/testNotifications.js";
import type * as notifications_triggers_comments from "../notifications/triggers/comments.js";
import type * as notifications_triggers_competitions from "../notifications/triggers/competitions.js";
import type * as notifications_triggers_tasks from "../notifications/triggers/tasks.js";
import type * as notifications_types from "../notifications/types.js";
import type * as refunds_api from "../refunds/api.js";
import type * as reminders_api from "../reminders/api.js";
import type * as sponsorship_auctions_competitionSnapshot from "../sponsorship/auctions/competitionSnapshot.js";
import type * as sponsorship_auctions_emails from "../sponsorship/auctions/emails.js";
import type * as sponsorship_auctions_index from "../sponsorship/auctions/index.js";
import type * as sponsorship_auctions_lifecycle from "../sponsorship/auctions/lifecycle.js";
import type * as sponsorship_auctions_management from "../sponsorship/auctions/management.js";
import type * as sponsorship_auctions_reminders from "../sponsorship/auctions/reminders.js";
import type * as sponsorship_auctions_shared from "../sponsorship/auctions/shared.js";
import type * as sponsorship_auth_server from "../sponsorship/auth/server.js";
import type * as sponsorship_authAccounts from "../sponsorship/authAccounts.js";
import type * as sponsorship_emailQueue from "../sponsorship/emailQueue.js";
import type * as sponsorship_emails_SponsorInviteEmail from "../sponsorship/emails/SponsorInviteEmail.js";
import type * as sponsorship_emails_SponsorPortalOtpEmail from "../sponsorship/emails/SponsorPortalOtpEmail.js";
import type * as sponsorship_emails_SponsorshipAuctionActiveReminderEmail from "../sponsorship/emails/SponsorshipAuctionActiveReminderEmail.js";
import type * as sponsorship_emails_SponsorshipEbayAuctionOutbidEmail from "../sponsorship/emails/SponsorshipEbayAuctionOutbidEmail.js";
import type * as sponsorship_emails_SponsorshipInternalInvoiceEmail from "../sponsorship/emails/SponsorshipInternalInvoiceEmail.js";
import type * as sponsorship_emails_SponsorshipOutcomeEmail from "../sponsorship/emails/SponsorshipOutcomeEmail.js";
import type * as sponsorship_emails_SponsorshipScheduledEmail from "../sponsorship/emails/SponsorshipScheduledEmail.js";
import type * as sponsorship_emails_shared from "../sponsorship/emails/shared.js";
import type * as sponsorship_lib_access from "../sponsorship/lib/access.js";
import type * as sponsorship_lib_auctionState from "../sponsorship/lib/auctionState.js";
import type * as sponsorship_lib_bidPlacement from "../sponsorship/lib/bidPlacement.js";
import type * as sponsorship_lib_bidding from "../sponsorship/lib/bidding.js";
import type * as sponsorship_lib_competitionSnapshot from "../sponsorship/lib/competitionSnapshot.js";
import type * as sponsorship_lib_emailTemplates from "../sponsorship/lib/emailTemplates.js";
import type * as sponsorship_lib_lifecycle from "../sponsorship/lib/lifecycle.js";
import type * as sponsorship_lib_validators from "../sponsorship/lib/validators.js";
import type * as sponsorship_lib_visibility from "../sponsorship/lib/visibility.js";
import type * as sponsorship_node from "../sponsorship/node.js";
import type * as sponsorship_portal_auctions from "../sponsorship/portal/auctions.js";
import type * as sponsorship_portal_auth from "../sponsorship/portal/auth.js";
import type * as sponsorship_portal_index from "../sponsorship/portal/index.js";
import type * as sponsorship_portal_shared from "../sponsorship/portal/shared.js";
import type * as sponsorship_sponsors from "../sponsorship/sponsors.js";
import type * as tasks_access from "../tasks/access.js";
import type * as tasks_api from "../tasks/api.js";
import type * as tasks_approvalLogic from "../tasks/approvalLogic.js";
import type * as tasks_approvals from "../tasks/approvals.js";
import type * as tasks_creation from "../tasks/creation.js";
import type * as tasks_deletion from "../tasks/deletion.js";
import type * as tasks_dueDate from "../tasks/dueDate.js";
import type * as tasks_format from "../tasks/format.js";
import type * as tasks_hydration from "../tasks/hydration.js";
import type * as tasks_mutations from "../tasks/mutations.js";
import type * as tasks_patch from "../tasks/patch.js";
import type * as tasks_queries from "../tasks/queries.js";
import type * as tasks_relations from "../tasks/relations.js";
import type * as tasks_relationsLogic from "../tasks/relationsLogic.js";
import type * as tasks_transforms from "../tasks/transforms.js";
import type * as test_utils_convexError from "../test_utils/convexError.js";
import type * as updates_api from "../updates/api.js";
import type * as webhooks_azureEmailEvents from "../webhooks/azureEmailEvents.js";
import type * as webhooks_discordInteractions from "../webhooks/discordInteractions.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  "comments/api": typeof comments_api;
  "competitions/access": typeof competitions_access;
  "competitions/api": typeof competitions_api;
  "competitions/nodeActions": typeof competitions_nodeActions;
  "competitions/weekendOverrides": typeof competitions_weekendOverrides;
  "core/admin": typeof core_admin;
  "core/auth": typeof core_auth;
  "core/labels": typeof core_labels;
  "core/phases": typeof core_phases;
  "core/seed": typeof core_seed;
  "core/teams": typeof core_teams;
  "core/userThemeSettings": typeof core_userThemeSettings;
  "core/users": typeof core_users;
  "core/views": typeof core_views;
  crons: typeof crons;
  "discord/actions": typeof discord_actions;
  "discord/api": typeof discord_api;
  "discord/client": typeof discord_client;
  "discord/commands": typeof discord_commands;
  "discord/config": typeof discord_config;
  "discord/handler": typeof discord_handler;
  "discord/interactions": typeof discord_interactions;
  "discord/rest": typeof discord_rest;
  "discord/slashCommands": typeof discord_slashCommands;
  "emailQueue/api": typeof emailQueue_api;
  "emailQueue/counters": typeof emailQueue_counters;
  "emailQueue/diagnostics": typeof emailQueue_diagnostics;
  "emailQueue/enqueue": typeof emailQueue_enqueue;
  "emailQueue/pool": typeof emailQueue_pool;
  "emailQueue/types": typeof emailQueue_types;
  "emailQueue/worker": typeof emailQueue_worker;
  "emails/NotificationDigestEmail": typeof emails_NotificationDigestEmail;
  "emails/NotificationEmail": typeof emails_NotificationEmail;
  "emails/shared": typeof emails_shared;
  http: typeof http;
  "integrations/canva/actions": typeof integrations_canva_actions;
  "integrations/canva/client/client": typeof integrations_canva_client_client;
  "integrations/canva/client/client/client/index": typeof integrations_canva_client_client_client_index;
  "integrations/canva/index": typeof integrations_canva_index;
  "integrations/canva/lib/helpers": typeof integrations_canva_lib_helpers;
  "integrations/canva/sharing": typeof integrations_canva_sharing;
  "integrations/google/client/sheetsClient": typeof integrations_google_client_sheetsClient;
  "integrations/google/index": typeof integrations_google_index;
  "integrations/google/sheets": typeof integrations_google_sheets;
  "integrations/google/sheetsQueries": typeof integrations_google_sheetsQueries;
  "integrations/linkedActions": typeof integrations_linkedActions;
  "integrations/linkedActions/config": typeof integrations_linkedActions_config;
  "integrations/linkedActions/permissions": typeof integrations_linkedActions_permissions;
  "integrations/linkedActions/runners": typeof integrations_linkedActions_runners;
  "integrations/linkedActions/shapes": typeof integrations_linkedActions_shapes;
  "integrations/oauth/flow": typeof integrations_oauth_flow;
  "integrations/oauth/index": typeof integrations_oauth_index;
  "integrations/oauth/providers": typeof integrations_oauth_providers;
  "integrations/services": typeof integrations_services;
  "integrations/tokens": typeof integrations_tokens;
  "integrations/tokens/runtime": typeof integrations_tokens_runtime;
  "integrations/tokens/tokenDefinition": typeof integrations_tokens_tokenDefinition;
  "integrations/tokens/types": typeof integrations_tokens_types;
  "integrations/types": typeof integrations_types;
  "integrations/wca/actions": typeof integrations_wca_actions;
  "integrations/wca/client/client": typeof integrations_wca_client_client;
  "integrations/wca/client/client/client/index": typeof integrations_wca_client_client_client_index;
  "integrations/wca/index": typeof integrations_wca_index;
  "integrations/wca/lib/registrations": typeof integrations_wca_lib_registrations;
  "integrations/wca/schedule": typeof integrations_wca_schedule;
  "integrations/wca/twoFactor": typeof integrations_wca_twoFactor;
  "lib/avatarResolver": typeof lib_avatarResolver;
  "lib/commentParentId": typeof lib_commentParentId;
  "lib/constants": typeof lib_constants;
  "lib/defaultAvatar": typeof lib_defaultAvatar;
  "lib/deploymentGuard": typeof lib_deploymentGuard;
  "lib/email": typeof lib_email;
  "lib/oauth": typeof lib_oauth;
  "lib/permissions/authn": typeof lib_permissions_authn;
  "lib/permissions/index": typeof lib_permissions_index;
  "lib/permissions/policies": typeof lib_permissions_policies;
  "lib/permissions/require": typeof lib_permissions_require;
  "lib/permissions/resources": typeof lib_permissions_resources;
  "lib/permissions/teams": typeof lib_permissions_teams;
  "lib/refunds": typeof lib_refunds;
  "lib/retry": typeof lib_retry;
  "lib/sanitize": typeof lib_sanitize;
  "lib/seedData": typeof lib_seedData;
  "lib/siteUrls": typeof lib_siteUrls;
  "lib/transforms": typeof lib_transforms;
  "lib/types": typeof lib_types;
  "lib/validators": typeof lib_validators;
  "migrations/renameNotificationTypes": typeof migrations_renameNotificationTypes;
  "notifications/api": typeof notifications_api;
  "notifications/catalog": typeof notifications_catalog;
  "notifications/discord/actions": typeof notifications_discord_actions;
  "notifications/discord/context": typeof notifications_discord_context;
  "notifications/discord/delivery": typeof notifications_discord_delivery;
  "notifications/discord/message": typeof notifications_discord_message;
  "notifications/discord/notifications/commentAdded": typeof notifications_discord_notifications_commentAdded;
  "notifications/discord/notifications/commentReplied": typeof notifications_discord_notifications_commentReplied;
  "notifications/discord/notifications/competitionPhaseChanged": typeof notifications_discord_notifications_competitionPhaseChanged;
  "notifications/discord/notifications/dueDateApproaching": typeof notifications_discord_notifications_dueDateApproaching;
  "notifications/discord/notifications/dueDateChanged": typeof notifications_discord_notifications_dueDateChanged;
  "notifications/discord/notifications/dueDateOverdue": typeof notifications_discord_notifications_dueDateOverdue;
  "notifications/discord/notifications/index": typeof notifications_discord_notifications_index;
  "notifications/discord/notifications/progressUpdateAdded": typeof notifications_discord_notifications_progressUpdateAdded;
  "notifications/discord/notifications/relationBlocked": typeof notifications_discord_notifications_relationBlocked;
  "notifications/discord/notifications/relationUnblocked": typeof notifications_discord_notifications_relationUnblocked;
  "notifications/discord/notifications/reminderTriggered": typeof notifications_discord_notifications_reminderTriggered;
  "notifications/discord/notifications/taskApproved": typeof notifications_discord_notifications_taskApproved;
  "notifications/discord/notifications/taskAssigned": typeof notifications_discord_notifications_taskAssigned;
  "notifications/discord/notifications/taskAwaitingReview": typeof notifications_discord_notifications_taskAwaitingReview;
  "notifications/discord/notifications/taskMentioned": typeof notifications_discord_notifications_taskMentioned;
  "notifications/discord/notifications/taskPriorityChanged": typeof notifications_discord_notifications_taskPriorityChanged;
  "notifications/discord/notifications/taskStatusChanged": typeof notifications_discord_notifications_taskStatusChanged;
  "notifications/discord/notifications/taskUnapproved": typeof notifications_discord_notifications_taskUnapproved;
  "notifications/discord/notifications/taskUnassigned": typeof notifications_discord_notifications_taskUnassigned;
  "notifications/discord/registry": typeof notifications_discord_registry;
  "notifications/discord/types": typeof notifications_discord_types;
  "notifications/discord/utils": typeof notifications_discord_utils;
  "notifications/emit": typeof notifications_emit;
  "notifications/index": typeof notifications_index;
  "notifications/internal": typeof notifications_internal;
  "notifications/lib/cleanup": typeof notifications_lib_cleanup;
  "notifications/lib/entities": typeof notifications_lib_entities;
  "notifications/lib/notificationAccess": typeof notifications_lib_notificationAccess;
  "notifications/lib/notificationBuilders": typeof notifications_lib_notificationBuilders;
  "notifications/lib/notificationDueDates": typeof notifications_lib_notificationDueDates;
  "notifications/lib/notificationTemplates": typeof notifications_lib_notificationTemplates;
  "notifications/lib/notificationTypes": typeof notifications_lib_notificationTypes;
  "notifications/lib/payload": typeof notifications_lib_payload;
  "notifications/lib/recipientCollection": typeof notifications_lib_recipientCollection;
  "notifications/lib/validators": typeof notifications_lib_validators;
  "notifications/lib/watcherPolicy": typeof notifications_lib_watcherPolicy;
  "notifications/lib/watcherRecipients": typeof notifications_lib_watcherRecipients;
  "notifications/recipients/expand": typeof notifications_recipients_expand;
  "notifications/subscriptions": typeof notifications_subscriptions;
  "notifications/testNotifications": typeof notifications_testNotifications;
  "notifications/triggers/comments": typeof notifications_triggers_comments;
  "notifications/triggers/competitions": typeof notifications_triggers_competitions;
  "notifications/triggers/tasks": typeof notifications_triggers_tasks;
  "notifications/types": typeof notifications_types;
  "refunds/api": typeof refunds_api;
  "reminders/api": typeof reminders_api;
  "sponsorship/auctions/competitionSnapshot": typeof sponsorship_auctions_competitionSnapshot;
  "sponsorship/auctions/emails": typeof sponsorship_auctions_emails;
  "sponsorship/auctions/index": typeof sponsorship_auctions_index;
  "sponsorship/auctions/lifecycle": typeof sponsorship_auctions_lifecycle;
  "sponsorship/auctions/management": typeof sponsorship_auctions_management;
  "sponsorship/auctions/reminders": typeof sponsorship_auctions_reminders;
  "sponsorship/auctions/shared": typeof sponsorship_auctions_shared;
  "sponsorship/auth/server": typeof sponsorship_auth_server;
  "sponsorship/authAccounts": typeof sponsorship_authAccounts;
  "sponsorship/emailQueue": typeof sponsorship_emailQueue;
  "sponsorship/emails/SponsorInviteEmail": typeof sponsorship_emails_SponsorInviteEmail;
  "sponsorship/emails/SponsorPortalOtpEmail": typeof sponsorship_emails_SponsorPortalOtpEmail;
  "sponsorship/emails/SponsorshipAuctionActiveReminderEmail": typeof sponsorship_emails_SponsorshipAuctionActiveReminderEmail;
  "sponsorship/emails/SponsorshipEbayAuctionOutbidEmail": typeof sponsorship_emails_SponsorshipEbayAuctionOutbidEmail;
  "sponsorship/emails/SponsorshipInternalInvoiceEmail": typeof sponsorship_emails_SponsorshipInternalInvoiceEmail;
  "sponsorship/emails/SponsorshipOutcomeEmail": typeof sponsorship_emails_SponsorshipOutcomeEmail;
  "sponsorship/emails/SponsorshipScheduledEmail": typeof sponsorship_emails_SponsorshipScheduledEmail;
  "sponsorship/emails/shared": typeof sponsorship_emails_shared;
  "sponsorship/lib/access": typeof sponsorship_lib_access;
  "sponsorship/lib/auctionState": typeof sponsorship_lib_auctionState;
  "sponsorship/lib/bidPlacement": typeof sponsorship_lib_bidPlacement;
  "sponsorship/lib/bidding": typeof sponsorship_lib_bidding;
  "sponsorship/lib/competitionSnapshot": typeof sponsorship_lib_competitionSnapshot;
  "sponsorship/lib/emailTemplates": typeof sponsorship_lib_emailTemplates;
  "sponsorship/lib/lifecycle": typeof sponsorship_lib_lifecycle;
  "sponsorship/lib/validators": typeof sponsorship_lib_validators;
  "sponsorship/lib/visibility": typeof sponsorship_lib_visibility;
  "sponsorship/node": typeof sponsorship_node;
  "sponsorship/portal/auctions": typeof sponsorship_portal_auctions;
  "sponsorship/portal/auth": typeof sponsorship_portal_auth;
  "sponsorship/portal/index": typeof sponsorship_portal_index;
  "sponsorship/portal/shared": typeof sponsorship_portal_shared;
  "sponsorship/sponsors": typeof sponsorship_sponsors;
  "tasks/access": typeof tasks_access;
  "tasks/api": typeof tasks_api;
  "tasks/approvalLogic": typeof tasks_approvalLogic;
  "tasks/approvals": typeof tasks_approvals;
  "tasks/creation": typeof tasks_creation;
  "tasks/deletion": typeof tasks_deletion;
  "tasks/dueDate": typeof tasks_dueDate;
  "tasks/format": typeof tasks_format;
  "tasks/hydration": typeof tasks_hydration;
  "tasks/mutations": typeof tasks_mutations;
  "tasks/patch": typeof tasks_patch;
  "tasks/queries": typeof tasks_queries;
  "tasks/relations": typeof tasks_relations;
  "tasks/relationsLogic": typeof tasks_relationsLogic;
  "tasks/transforms": typeof tasks_transforms;
  "test_utils/convexError": typeof test_utils_convexError;
  "updates/api": typeof updates_api;
  "webhooks/azureEmailEvents": typeof webhooks_azureEmailEvents;
  "webhooks/discordInteractions": typeof webhooks_discordInteractions;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  crons: import("@convex-dev/crons/_generated/component.js").ComponentApi<"crons">;
  emailWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"emailWorkpool">;
  sponsorAuth: import("../sponsorship/auth/component/sponsorAuth/_generated/component.js").ComponentApi<"sponsorAuth">;
};
