/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as access_authorize from "../access/authorize.js";
import type * as access_scopedObject from "../access/scopedObject.js";
import type * as admin_discord from "../admin/discord.js";
import type * as admin_sponsorImpersonation from "../admin/sponsorImpersonation.js";
import type * as auth from "../auth.js";
import type * as comments_access from "../comments/access.js";
import type * as comments_client from "../comments/client.js";
import type * as comments_mentionTokens from "../comments/mentionTokens.js";
import type * as comments_mentions from "../comments/mentions.js";
import type * as comments_mutations from "../comments/mutations.js";
import type * as comments_queries from "../comments/queries.js";
import type * as comments_validators from "../comments/validators.js";
import type * as competitions_access from "../competitions/access.js";
import type * as competitions_calendar from "../competitions/calendar.js";
import type * as competitions_dates from "../competitions/dates.js";
import type * as competitions_invites_model from "../competitions/invites/model.js";
import type * as competitions_invites_mutations from "../competitions/invites/mutations.js";
import type * as competitions_invites_queries from "../competitions/invites/queries.js";
import type * as competitions_invites_validators from "../competitions/invites/validators.js";
import type * as competitions_mutations from "../competitions/mutations.js";
import type * as competitions_queries from "../competitions/queries.js";
import type * as competitions_validators from "../competitions/validators.js";
import type * as competitions_weekendSlots_mutations from "../competitions/weekendSlots/mutations.js";
import type * as competitions_weekendSlots_validators from "../competitions/weekendSlots/validators.js";
import type * as competitions_weekends from "../competitions/weekends.js";
import type * as crons from "../crons.js";
import type * as dashboard_queries from "../dashboard/queries.js";
import type * as deploymentContext from "../deploymentContext.js";
import type * as emoji from "../emoji.js";
import type * as env from "../env.js";
import type * as envConfig from "../envConfig.js";
import type * as envTypes from "../envTypes.js";
import type * as errors from "../errors.js";
import type * as http from "../http.js";
import type * as impersonation_internal from "../impersonation/internal.js";
import type * as impersonation_model from "../impersonation/model.js";
import type * as impersonation_mutations from "../impersonation/mutations.js";
import type * as impersonation_queries from "../impersonation/queries.js";
import type * as impersonation_validators from "../impersonation/validators.js";
import type * as integrations_constants from "../integrations/constants.js";
import type * as integrations_errorPayload from "../integrations/errorPayload.js";
import type * as integrations_jsonBoundary from "../integrations/jsonBoundary.js";
import type * as integrations_linkObjectResource from "../integrations/linkObjectResource.js";
import type * as integrations_objectResources from "../integrations/objectResources.js";
import type * as integrations_objectResourcesModel from "../integrations/objectResourcesModel.js";
import type * as integrations_taskIntegrations_constants from "../integrations/taskIntegrations/constants.js";
import type * as integrations_taskIntegrations_mutations from "../integrations/taskIntegrations/mutations.js";
import type * as integrations_taskIntegrations_pluginContract from "../integrations/taskIntegrations/pluginContract.js";
import type * as integrations_taskIntegrations_queries from "../integrations/taskIntegrations/queries.js";
import type * as integrations_taskIntegrations_registry from "../integrations/taskIntegrations/registry.js";
import type * as integrations_taskIntegrations_runResource from "../integrations/taskIntegrations/runResource.js";
import type * as integrations_taskIntegrations_runner from "../integrations/taskIntegrations/runner.js";
import type * as integrations_taskIntegrations_runnerQueries from "../integrations/taskIntegrations/runnerQueries.js";
import type * as integrations_taskIntegrations_templates from "../integrations/taskIntegrations/templates.js";
import type * as integrations_taskIntegrations_validators from "../integrations/taskIntegrations/validators.js";
import type * as integrations_tokens from "../integrations/tokens.js";
import type * as integrations_tokensStore from "../integrations/tokensStore.js";
import type * as integrations_validators from "../integrations/validators.js";
import type * as notifications_actionCodec from "../notifications/actionCodec.js";
import type * as notifications_actions from "../notifications/actions.js";
import type * as notifications_branding from "../notifications/branding.js";
import type * as notifications_dispatch from "../notifications/dispatch.js";
import type * as notifications_due from "../notifications/due.js";
import type * as notifications_embeds from "../notifications/embeds.js";
import type * as notifications_enrichers from "../notifications/enrichers.js";
import type * as notifications_events from "../notifications/events.js";
import type * as notifications_interactions from "../notifications/interactions.js";
import type * as notifications_localTime from "../notifications/localTime.js";
import type * as notifications_model from "../notifications/model.js";
import type * as notifications_nudge from "../notifications/nudge.js";
import type * as notifications_reminders from "../notifications/reminders.js";
import type * as notifications_types from "../notifications/types.js";
import type * as notifications_validators from "../notifications/validators.js";
import type * as permissions_principal from "../permissions/principal.js";
import type * as permissions_queries from "../permissions/queries.js";
import type * as permissions_shared from "../permissions/shared.js";
import type * as phases_colors from "../phases/colors.js";
import type * as phases_model from "../phases/model.js";
import type * as phases_mutations from "../phases/mutations.js";
import type * as phases_progress from "../phases/progress.js";
import type * as phases_queries from "../phases/queries.js";
import type * as phases_setCurrentPhase from "../phases/setCurrentPhase.js";
import type * as phases_validators from "../phases/validators.js";
import type * as plugins_canva_api from "../plugins/canva/api.js";
import type * as plugins_canva_backendPlugin from "../plugins/canva/backendPlugin.js";
import type * as plugins_canva_definition from "../plugins/canva/definition.js";
import type * as plugins_canva_helpers from "../plugins/canva/helpers.js";
import type * as plugins_canva_links from "../plugins/canva/links.js";
import type * as plugins_canva_mutations from "../plugins/canva/mutations.js";
import type * as plugins_canva_oauth from "../plugins/canva/oauth.js";
import type * as plugins_canva_openapiClient_client_index from "../plugins/canva/openapiClient/client/index.js";
import type * as plugins_canva_presets from "../plugins/canva/presets.js";
import type * as plugins_canva_runners from "../plugins/canva/runners.js";
import type * as plugins_certificates_plugin from "../plugins/certificates/plugin.js";
import type * as plugins_certificates_queries from "../plugins/certificates/queries.js";
import type * as plugins_certificates_workflows from "../plugins/certificates/workflows.js";
import type * as plugins_discord_actions from "../plugins/discord/actions.js";
import type * as plugins_discord_api from "../plugins/discord/api.js";
import type * as plugins_discord_channels from "../plugins/discord/channels.js";
import type * as plugins_discord_definition from "../plugins/discord/definition.js";
import type * as plugins_discord_members from "../plugins/discord/members.js";
import type * as plugins_discord_resources from "../plugins/discord/resources.js";
import type * as plugins_events_actions from "../plugins/events/actions.js";
import type * as plugins_events_concurrency from "../plugins/events/concurrency.js";
import type * as plugins_events_constants from "../plugins/events/constants.js";
import type * as plugins_events_mutations from "../plugins/events/mutations.js";
import type * as plugins_events_queries from "../plugins/events/queries.js";
import type * as plugins_events_validators from "../plugins/events/validators.js";
import type * as plugins_events_wcaSchedule from "../plugins/events/wcaSchedule.js";
import type * as plugins_google_definition from "../plugins/google/definition.js";
import type * as plugins_google_oauth from "../plugins/google/oauth.js";
import type * as plugins_oauth from "../plugins/oauth.js";
import type * as plugins_oauthProvider from "../plugins/oauthProvider.js";
import type * as plugins_oauthRegistry from "../plugins/oauthRegistry.js";
import type * as plugins_registry from "../plugins/registry.js";
import type * as plugins_sheets_constants from "../plugins/sheets/constants.js";
import type * as plugins_sheets_definition from "../plugins/sheets/definition.js";
import type * as plugins_sheets_googleApi from "../plugins/sheets/googleApi.js";
import type * as plugins_sheets_resources from "../plugins/sheets/resources.js";
import type * as plugins_sheets_runners from "../plugins/sheets/runners.js";
import type * as plugins_sheets_schedule from "../plugins/sheets/schedule.js";
import type * as plugins_sheets_tokens from "../plugins/sheets/tokens.js";
import type * as plugins_socialMedia_dashboard from "../plugins/socialMedia/dashboard.js";
import type * as plugins_socialMedia_lib_fetchFromWca from "../plugins/socialMedia/lib/fetchFromWca.js";
import type * as plugins_socialMedia_lib_sponsorDetection from "../plugins/socialMedia/lib/sponsorDetection.js";
import type * as plugins_socialMedia_resolveHqLinks from "../plugins/socialMedia/resolveHqLinks.js";
import type * as plugins_sponsor_admin_auctionSettings from "../plugins/sponsor/admin/auctionSettings.js";
import type * as plugins_sponsor_admin_auctions_competitionSnapshot from "../plugins/sponsor/admin/auctions/competitionSnapshot.js";
import type * as plugins_sponsor_admin_auctions_emails from "../plugins/sponsor/admin/auctions/emails.js";
import type * as plugins_sponsor_admin_auctions_lifecycle from "../plugins/sponsor/admin/auctions/lifecycle.js";
import type * as plugins_sponsor_admin_auctions_management from "../plugins/sponsor/admin/auctions/management.js";
import type * as plugins_sponsor_admin_auctions_migrations from "../plugins/sponsor/admin/auctions/migrations.js";
import type * as plugins_sponsor_admin_auctions_reminders from "../plugins/sponsor/admin/auctions/reminders.js";
import type * as plugins_sponsor_admin_auctions_scheduledFunctions from "../plugins/sponsor/admin/auctions/scheduledFunctions.js";
import type * as plugins_sponsor_admin_auctions_shared from "../plugins/sponsor/admin/auctions/shared.js";
import type * as plugins_sponsor_admin_contacts from "../plugins/sponsor/admin/contacts.js";
import type * as plugins_sponsor_admin_propertyStatus from "../plugins/sponsor/admin/propertyStatus.js";
import type * as plugins_sponsor_admin_sponsors from "../plugins/sponsor/admin/sponsors.js";
import type * as plugins_sponsor_auth_accounts from "../plugins/sponsor/auth/accounts.js";
import type * as plugins_sponsor_auth_server from "../plugins/sponsor/auth/server.js";
import type * as plugins_sponsor_emails__build from "../plugins/sponsor/emails/_build.js";
import type * as plugins_sponsor_emails__components_anti_sniping_note from "../plugins/sponsor/emails/_components/anti_sniping_note.js";
import type * as plugins_sponsor_emails__components_info_stack from "../plugins/sponsor/emails/_components/info_stack.js";
import type * as plugins_sponsor_emails__components_internal_invoice_email from "../plugins/sponsor/emails/_components/internal_invoice_email.js";
import type * as plugins_sponsor_emails__components_lifecycle_email from "../plugins/sponsor/emails/_components/lifecycle_email.js";
import type * as plugins_sponsor_emails__components_outcome_email from "../plugins/sponsor/emails/_components/outcome_email.js";
import type * as plugins_sponsor_emails__components_sponsorship_email_body from "../plugins/sponsor/emails/_components/sponsorship_email_body.js";
import type * as plugins_sponsor_emails__design from "../plugins/sponsor/emails/_design.js";
import type * as plugins_sponsor_emails_auction_active_reminder from "../plugins/sponsor/emails/auction_active_reminder.js";
import type * as plugins_sponsor_emails_auction_closed_none from "../plugins/sponsor/emails/auction_closed_none.js";
import type * as plugins_sponsor_emails_auction_closed_outbid from "../plugins/sponsor/emails/auction_closed_outbid.js";
import type * as plugins_sponsor_emails_auction_closed_winner from "../plugins/sponsor/emails/auction_closed_winner.js";
import type * as plugins_sponsor_emails_auction_ebay_outbid from "../plugins/sponsor/emails/auction_ebay_outbid.js";
import type * as plugins_sponsor_emails_auction_scheduled from "../plugins/sponsor/emails/auction_scheduled.js";
import type * as plugins_sponsor_emails_auction_started from "../plugins/sponsor/emails/auction_started.js";
import type * as plugins_sponsor_emails_copy from "../plugins/sponsor/emails/copy.js";
import type * as plugins_sponsor_emails_dedup from "../plugins/sponsor/emails/dedup.js";
import type * as plugins_sponsor_emails_fixtures from "../plugins/sponsor/emails/fixtures.js";
import type * as plugins_sponsor_emails_index from "../plugins/sponsor/emails/index.js";
import type * as plugins_sponsor_emails_internal_invoice_no_winner from "../plugins/sponsor/emails/internal_invoice_no_winner.js";
import type * as plugins_sponsor_emails_internal_invoice_winner from "../plugins/sponsor/emails/internal_invoice_winner.js";
import type * as plugins_sponsor_emails_invite from "../plugins/sponsor/emails/invite.js";
import type * as plugins_sponsor_emails_otp_sign_in from "../plugins/sponsor/emails/otp_sign_in.js";
import type * as plugins_sponsor_emails_render from "../plugins/sponsor/emails/render.js";
import type * as plugins_sponsor_emails_send from "../plugins/sponsor/emails/send.js";
import type * as plugins_sponsor_emails_sendBatch from "../plugins/sponsor/emails/sendBatch.js";
import type * as plugins_sponsor_emails_sender from "../plugins/sponsor/emails/sender.js";
import type * as plugins_sponsor_emails_types from "../plugins/sponsor/emails/types.js";
import type * as plugins_sponsor_http from "../plugins/sponsor/http.js";
import type * as plugins_sponsor_impersonation from "../plugins/sponsor/impersonation.js";
import type * as plugins_sponsor_integrations_wca_fetchDetails from "../plugins/sponsor/integrations/wca/fetchDetails.js";
import type * as plugins_sponsor_integrations_wca_search from "../plugins/sponsor/integrations/wca/search.js";
import type * as plugins_sponsor_lib_auctionState from "../plugins/sponsor/lib/auctionState.js";
import type * as plugins_sponsor_lib_auctionSubject from "../plugins/sponsor/lib/auctionSubject.js";
import type * as plugins_sponsor_lib_bidPlacement from "../plugins/sponsor/lib/bidPlacement.js";
import type * as plugins_sponsor_lib_bidding from "../plugins/sponsor/lib/bidding.js";
import type * as plugins_sponsor_lib_competitionSnapshot from "../plugins/sponsor/lib/competitionSnapshot.js";
import type * as plugins_sponsor_lib_competitionSponsorOverrides from "../plugins/sponsor/lib/competitionSponsorOverrides.js";
import type * as plugins_sponsor_lib_competitionSponsorStatus from "../plugins/sponsor/lib/competitionSponsorStatus.js";
import type * as plugins_sponsor_lib_contacts from "../plugins/sponsor/lib/contacts.js";
import type * as plugins_sponsor_lib_currency from "../plugins/sponsor/lib/currency.js";
import type * as plugins_sponsor_lib_lifecycle from "../plugins/sponsor/lib/lifecycle.js";
import type * as plugins_sponsor_lib_sponsorBidStatus from "../plugins/sponsor/lib/sponsorBidStatus.js";
import type * as plugins_sponsor_lib_sponsorOwnedCompetitions from "../plugins/sponsor/lib/sponsorOwnedCompetitions.js";
import type * as plugins_sponsor_lib_sponsorshipLifecycle from "../plugins/sponsor/lib/sponsorshipLifecycle.js";
import type * as plugins_sponsor_lib_types from "../plugins/sponsor/lib/types.js";
import type * as plugins_sponsor_lib_validators from "../plugins/sponsor/lib/validators.js";
import type * as plugins_sponsor_lib_visibility from "../plugins/sponsor/lib/visibility.js";
import type * as plugins_sponsor_lib_wcaIntegration from "../plugins/sponsor/lib/wcaIntegration.js";
import type * as plugins_sponsor_plugin from "../plugins/sponsor/plugin.js";
import type * as plugins_sponsor_portal_auctions from "../plugins/sponsor/portal/auctions.js";
import type * as plugins_sponsor_portal_auth from "../plugins/sponsor/portal/auth.js";
import type * as plugins_sponsor_portal_shared from "../plugins/sponsor/portal/shared.js";
import type * as plugins_sponsor_portal_sponsorships from "../plugins/sponsor/portal/sponsorships.js";
import type * as plugins_sponsor_sanitize from "../plugins/sponsor/sanitize.js";
import type * as plugins_sponsor_siteUrls from "../plugins/sponsor/siteUrls.js";
import type * as plugins_sponsor_testing_testHelpers from "../plugins/sponsor/testing/testHelpers.js";
import type * as plugins_sponsor_validators from "../plugins/sponsor/validators.js";
import type * as plugins_validators from "../plugins/validators.js";
import type * as plugins_wca_api from "../plugins/wca/api.js";
import type * as plugins_wca_client from "../plugins/wca/client.js";
import type * as plugins_wca_competitionLink from "../plugins/wca/competitionLink.js";
import type * as plugins_wca_competitionOptions from "../plugins/wca/competitionOptions.js";
import type * as plugins_wca_definition from "../plugins/wca/definition.js";
import type * as plugins_wca_managedCompetitions from "../plugins/wca/managedCompetitions.js";
import type * as plugins_wca_oauth from "../plugins/wca/oauth.js";
import type * as plugins_wca_openapiClient_client_index from "../plugins/wca/openapiClient/client/index.js";
import type * as plugins_wca_registrationsLib from "../plugins/wca/registrationsLib.js";
import type * as plugins_wca_resources from "../plugins/wca/resources.js";
import type * as plugins_wca_scheduleTransferCore from "../plugins/wca/scheduleTransferCore.js";
import type * as plugins_wca_twoFactor from "../plugins/wca/twoFactor.js";
import type * as plugins_wca_wcifCompetition from "../plugins/wca/wcifCompetition.js";
import type * as projectWorkflows_constants from "../projectWorkflows/constants.js";
import type * as projectWorkflows_mutations from "../projectWorkflows/mutations.js";
import type * as projectWorkflows_queries from "../projectWorkflows/queries.js";
import type * as projectWorkflows_registry from "../projectWorkflows/registry.js";
import type * as projectWorkflows_runner from "../projectWorkflows/runner.js";
import type * as projectWorkflows_runnerQueries from "../projectWorkflows/runnerQueries.js";
import type * as projectWorkflows_types from "../projectWorkflows/types.js";
import type * as projectWorkflows_validators from "../projectWorkflows/validators.js";
import type * as projects_access from "../projects/access.js";
import type * as projects_model from "../projects/model.js";
import type * as projects_mutations from "../projects/mutations.js";
import type * as projects_queries from "../projects/queries.js";
import type * as projects_statuses from "../projects/statuses.js";
import type * as projects_validators from "../projects/validators.js";
import type * as reactions from "../reactions.js";
import type * as refunds_actions from "../refunds/actions.js";
import type * as refunds_api from "../refunds/api.js";
import type * as refunds_logic from "../refunds/logic.js";
import type * as refunds_validators from "../refunds/validators.js";
import type * as seed_model from "../seed/model.js";
import type * as seed_mutations from "../seed/mutations.js";
import type * as sendEmails from "../sendEmails.js";
import type * as subscriptions_index from "../subscriptions/index.js";
import type * as subscriptions_validators from "../subscriptions/validators.js";
import type * as tasks_access from "../tasks/access.js";
import type * as tasks_assignees from "../tasks/assignees.js";
import type * as tasks_blockers_counts from "../tasks/blockers/counts.js";
import type * as tasks_blockers_dependency from "../tasks/blockers/dependency.js";
import type * as tasks_blockers_loader from "../tasks/blockers/loader.js";
import type * as tasks_blockers_mutations from "../tasks/blockers/mutations.js";
import type * as tasks_blockers_queries from "../tasks/blockers/queries.js";
import type * as tasks_blockers_root from "../tasks/blockers/root.js";
import type * as tasks_blockers_validators from "../tasks/blockers/validators.js";
import type * as tasks_board from "../tasks/board.js";
import type * as tasks_filterChips from "../tasks/filterChips.js";
import type * as tasks_flowView from "../tasks/flowView.js";
import type * as tasks_hierarchy from "../tasks/hierarchy.js";
import type * as tasks_inlineRow from "../tasks/inlineRow.js";
import type * as tasks_kind from "../tasks/kind.js";
import type * as tasks_labels_constants from "../tasks/labels/constants.js";
import type * as tasks_labels_model from "../tasks/labels/model.js";
import type * as tasks_labels_mutations from "../tasks/labels/mutations.js";
import type * as tasks_labels_queries from "../tasks/labels/queries.js";
import type * as tasks_labels_validators from "../tasks/labels/validators.js";
import type * as tasks_mutations from "../tasks/mutations.js";
import type * as tasks_overdue from "../tasks/overdue.js";
import type * as tasks_queries from "../tasks/queries.js";
import type * as tasks_reviews_mutations from "../tasks/reviews/mutations.js";
import type * as tasks_reviews_preview from "../tasks/reviews/preview.js";
import type * as tasks_reviews_queries from "../tasks/reviews/queries.js";
import type * as tasks_reviews_reviewState from "../tasks/reviews/reviewState.js";
import type * as tasks_reviews_validators from "../tasks/reviews/validators.js";
import type * as tasks_status_recompute from "../tasks/status/recompute.js";
import type * as tasks_status_resolver from "../tasks/status/resolver.js";
import type * as tasks_status_rules from "../tasks/status/rules.js";
import type * as tasks_status_validators from "../tasks/status/validators.js";
import type * as tasks_subtaskView from "../tasks/subtaskView.js";
import type * as tasks_validators from "../tasks/validators.js";
import type * as tasks_view from "../tasks/view.js";
import type * as tasks_watchers from "../tasks/watchers.js";
import type * as teams_discordChannels from "../teams/discordChannels.js";
import type * as teams_model from "../teams/model.js";
import type * as teams_mutations from "../teams/mutations.js";
import type * as teams_queries from "../teams/queries.js";
import type * as teams_validators from "../teams/validators.js";
import type * as templates_mutations from "../templates/mutations.js";
import type * as templates_queries from "../templates/queries.js";
import type * as templates_registry from "../templates/registry.js";
import type * as templates_resolver from "../templates/resolver.js";
import type * as templates_validators from "../templates/validators.js";
import type * as testHelpers from "../testHelpers.js";
import type * as testing_discordNotificationTestEnv from "../testing/discordNotificationTestEnv.js";
import type * as tokens from "../tokens.js";
import type * as updates_model from "../updates/model.js";
import type * as updates_mutations from "../updates/mutations.js";
import type * as updates_queries from "../updates/queries.js";
import type * as updates_validators from "../updates/validators.js";
import type * as urls from "../urls.js";
import type * as users_adminModel from "../users/adminModel.js";
import type * as users_avatar from "../users/avatar.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_validators from "../users/validators.js";
import type * as utils from "../utils.js";
import type * as views_mutations from "../views/mutations.js";
import type * as views_queries from "../views/queries.js";
import type * as views_validators from "../views/validators.js";
import type * as wcaLogin_internal from "../wcaLogin/internal.js";
import type * as wcaLogin_queries from "../wcaLogin/queries.js";
import type * as wcaLogin_wcaLogin from "../wcaLogin/wcaLogin.js";
import type * as wcaLogin_wcaLoginPaths from "../wcaLogin/wcaLoginPaths.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "access/authorize": typeof access_authorize;
  "access/scopedObject": typeof access_scopedObject;
  "admin/discord": typeof admin_discord;
  "admin/sponsorImpersonation": typeof admin_sponsorImpersonation;
  auth: typeof auth;
  "comments/access": typeof comments_access;
  "comments/client": typeof comments_client;
  "comments/mentionTokens": typeof comments_mentionTokens;
  "comments/mentions": typeof comments_mentions;
  "comments/mutations": typeof comments_mutations;
  "comments/queries": typeof comments_queries;
  "comments/validators": typeof comments_validators;
  "competitions/access": typeof competitions_access;
  "competitions/calendar": typeof competitions_calendar;
  "competitions/dates": typeof competitions_dates;
  "competitions/invites/model": typeof competitions_invites_model;
  "competitions/invites/mutations": typeof competitions_invites_mutations;
  "competitions/invites/queries": typeof competitions_invites_queries;
  "competitions/invites/validators": typeof competitions_invites_validators;
  "competitions/mutations": typeof competitions_mutations;
  "competitions/queries": typeof competitions_queries;
  "competitions/validators": typeof competitions_validators;
  "competitions/weekendSlots/mutations": typeof competitions_weekendSlots_mutations;
  "competitions/weekendSlots/validators": typeof competitions_weekendSlots_validators;
  "competitions/weekends": typeof competitions_weekends;
  crons: typeof crons;
  "dashboard/queries": typeof dashboard_queries;
  deploymentContext: typeof deploymentContext;
  emoji: typeof emoji;
  env: typeof env;
  envConfig: typeof envConfig;
  envTypes: typeof envTypes;
  errors: typeof errors;
  http: typeof http;
  "impersonation/internal": typeof impersonation_internal;
  "impersonation/model": typeof impersonation_model;
  "impersonation/mutations": typeof impersonation_mutations;
  "impersonation/queries": typeof impersonation_queries;
  "impersonation/validators": typeof impersonation_validators;
  "integrations/constants": typeof integrations_constants;
  "integrations/errorPayload": typeof integrations_errorPayload;
  "integrations/jsonBoundary": typeof integrations_jsonBoundary;
  "integrations/linkObjectResource": typeof integrations_linkObjectResource;
  "integrations/objectResources": typeof integrations_objectResources;
  "integrations/objectResourcesModel": typeof integrations_objectResourcesModel;
  "integrations/taskIntegrations/constants": typeof integrations_taskIntegrations_constants;
  "integrations/taskIntegrations/mutations": typeof integrations_taskIntegrations_mutations;
  "integrations/taskIntegrations/pluginContract": typeof integrations_taskIntegrations_pluginContract;
  "integrations/taskIntegrations/queries": typeof integrations_taskIntegrations_queries;
  "integrations/taskIntegrations/registry": typeof integrations_taskIntegrations_registry;
  "integrations/taskIntegrations/runResource": typeof integrations_taskIntegrations_runResource;
  "integrations/taskIntegrations/runner": typeof integrations_taskIntegrations_runner;
  "integrations/taskIntegrations/runnerQueries": typeof integrations_taskIntegrations_runnerQueries;
  "integrations/taskIntegrations/templates": typeof integrations_taskIntegrations_templates;
  "integrations/taskIntegrations/validators": typeof integrations_taskIntegrations_validators;
  "integrations/tokens": typeof integrations_tokens;
  "integrations/tokensStore": typeof integrations_tokensStore;
  "integrations/validators": typeof integrations_validators;
  "notifications/actionCodec": typeof notifications_actionCodec;
  "notifications/actions": typeof notifications_actions;
  "notifications/branding": typeof notifications_branding;
  "notifications/dispatch": typeof notifications_dispatch;
  "notifications/due": typeof notifications_due;
  "notifications/embeds": typeof notifications_embeds;
  "notifications/enrichers": typeof notifications_enrichers;
  "notifications/events": typeof notifications_events;
  "notifications/interactions": typeof notifications_interactions;
  "notifications/localTime": typeof notifications_localTime;
  "notifications/model": typeof notifications_model;
  "notifications/nudge": typeof notifications_nudge;
  "notifications/reminders": typeof notifications_reminders;
  "notifications/types": typeof notifications_types;
  "notifications/validators": typeof notifications_validators;
  "permissions/principal": typeof permissions_principal;
  "permissions/queries": typeof permissions_queries;
  "permissions/shared": typeof permissions_shared;
  "phases/colors": typeof phases_colors;
  "phases/model": typeof phases_model;
  "phases/mutations": typeof phases_mutations;
  "phases/progress": typeof phases_progress;
  "phases/queries": typeof phases_queries;
  "phases/setCurrentPhase": typeof phases_setCurrentPhase;
  "phases/validators": typeof phases_validators;
  "plugins/canva/api": typeof plugins_canva_api;
  "plugins/canva/backendPlugin": typeof plugins_canva_backendPlugin;
  "plugins/canva/definition": typeof plugins_canva_definition;
  "plugins/canva/helpers": typeof plugins_canva_helpers;
  "plugins/canva/links": typeof plugins_canva_links;
  "plugins/canva/mutations": typeof plugins_canva_mutations;
  "plugins/canva/oauth": typeof plugins_canva_oauth;
  "plugins/canva/openapiClient/client/index": typeof plugins_canva_openapiClient_client_index;
  "plugins/canva/presets": typeof plugins_canva_presets;
  "plugins/canva/runners": typeof plugins_canva_runners;
  "plugins/certificates/plugin": typeof plugins_certificates_plugin;
  "plugins/certificates/queries": typeof plugins_certificates_queries;
  "plugins/certificates/workflows": typeof plugins_certificates_workflows;
  "plugins/discord/actions": typeof plugins_discord_actions;
  "plugins/discord/api": typeof plugins_discord_api;
  "plugins/discord/channels": typeof plugins_discord_channels;
  "plugins/discord/definition": typeof plugins_discord_definition;
  "plugins/discord/members": typeof plugins_discord_members;
  "plugins/discord/resources": typeof plugins_discord_resources;
  "plugins/events/actions": typeof plugins_events_actions;
  "plugins/events/concurrency": typeof plugins_events_concurrency;
  "plugins/events/constants": typeof plugins_events_constants;
  "plugins/events/mutations": typeof plugins_events_mutations;
  "plugins/events/queries": typeof plugins_events_queries;
  "plugins/events/validators": typeof plugins_events_validators;
  "plugins/events/wcaSchedule": typeof plugins_events_wcaSchedule;
  "plugins/google/definition": typeof plugins_google_definition;
  "plugins/google/oauth": typeof plugins_google_oauth;
  "plugins/oauth": typeof plugins_oauth;
  "plugins/oauthProvider": typeof plugins_oauthProvider;
  "plugins/oauthRegistry": typeof plugins_oauthRegistry;
  "plugins/registry": typeof plugins_registry;
  "plugins/sheets/constants": typeof plugins_sheets_constants;
  "plugins/sheets/definition": typeof plugins_sheets_definition;
  "plugins/sheets/googleApi": typeof plugins_sheets_googleApi;
  "plugins/sheets/resources": typeof plugins_sheets_resources;
  "plugins/sheets/runners": typeof plugins_sheets_runners;
  "plugins/sheets/schedule": typeof plugins_sheets_schedule;
  "plugins/sheets/tokens": typeof plugins_sheets_tokens;
  "plugins/socialMedia/dashboard": typeof plugins_socialMedia_dashboard;
  "plugins/socialMedia/lib/fetchFromWca": typeof plugins_socialMedia_lib_fetchFromWca;
  "plugins/socialMedia/lib/sponsorDetection": typeof plugins_socialMedia_lib_sponsorDetection;
  "plugins/socialMedia/resolveHqLinks": typeof plugins_socialMedia_resolveHqLinks;
  "plugins/sponsor/admin/auctionSettings": typeof plugins_sponsor_admin_auctionSettings;
  "plugins/sponsor/admin/auctions/competitionSnapshot": typeof plugins_sponsor_admin_auctions_competitionSnapshot;
  "plugins/sponsor/admin/auctions/emails": typeof plugins_sponsor_admin_auctions_emails;
  "plugins/sponsor/admin/auctions/lifecycle": typeof plugins_sponsor_admin_auctions_lifecycle;
  "plugins/sponsor/admin/auctions/management": typeof plugins_sponsor_admin_auctions_management;
  "plugins/sponsor/admin/auctions/migrations": typeof plugins_sponsor_admin_auctions_migrations;
  "plugins/sponsor/admin/auctions/reminders": typeof plugins_sponsor_admin_auctions_reminders;
  "plugins/sponsor/admin/auctions/scheduledFunctions": typeof plugins_sponsor_admin_auctions_scheduledFunctions;
  "plugins/sponsor/admin/auctions/shared": typeof plugins_sponsor_admin_auctions_shared;
  "plugins/sponsor/admin/contacts": typeof plugins_sponsor_admin_contacts;
  "plugins/sponsor/admin/propertyStatus": typeof plugins_sponsor_admin_propertyStatus;
  "plugins/sponsor/admin/sponsors": typeof plugins_sponsor_admin_sponsors;
  "plugins/sponsor/auth/accounts": typeof plugins_sponsor_auth_accounts;
  "plugins/sponsor/auth/server": typeof plugins_sponsor_auth_server;
  "plugins/sponsor/emails/_build": typeof plugins_sponsor_emails__build;
  "plugins/sponsor/emails/_components/anti_sniping_note": typeof plugins_sponsor_emails__components_anti_sniping_note;
  "plugins/sponsor/emails/_components/info_stack": typeof plugins_sponsor_emails__components_info_stack;
  "plugins/sponsor/emails/_components/internal_invoice_email": typeof plugins_sponsor_emails__components_internal_invoice_email;
  "plugins/sponsor/emails/_components/lifecycle_email": typeof plugins_sponsor_emails__components_lifecycle_email;
  "plugins/sponsor/emails/_components/outcome_email": typeof plugins_sponsor_emails__components_outcome_email;
  "plugins/sponsor/emails/_components/sponsorship_email_body": typeof plugins_sponsor_emails__components_sponsorship_email_body;
  "plugins/sponsor/emails/_design": typeof plugins_sponsor_emails__design;
  "plugins/sponsor/emails/auction_active_reminder": typeof plugins_sponsor_emails_auction_active_reminder;
  "plugins/sponsor/emails/auction_closed_none": typeof plugins_sponsor_emails_auction_closed_none;
  "plugins/sponsor/emails/auction_closed_outbid": typeof plugins_sponsor_emails_auction_closed_outbid;
  "plugins/sponsor/emails/auction_closed_winner": typeof plugins_sponsor_emails_auction_closed_winner;
  "plugins/sponsor/emails/auction_ebay_outbid": typeof plugins_sponsor_emails_auction_ebay_outbid;
  "plugins/sponsor/emails/auction_scheduled": typeof plugins_sponsor_emails_auction_scheduled;
  "plugins/sponsor/emails/auction_started": typeof plugins_sponsor_emails_auction_started;
  "plugins/sponsor/emails/copy": typeof plugins_sponsor_emails_copy;
  "plugins/sponsor/emails/dedup": typeof plugins_sponsor_emails_dedup;
  "plugins/sponsor/emails/fixtures": typeof plugins_sponsor_emails_fixtures;
  "plugins/sponsor/emails/index": typeof plugins_sponsor_emails_index;
  "plugins/sponsor/emails/internal_invoice_no_winner": typeof plugins_sponsor_emails_internal_invoice_no_winner;
  "plugins/sponsor/emails/internal_invoice_winner": typeof plugins_sponsor_emails_internal_invoice_winner;
  "plugins/sponsor/emails/invite": typeof plugins_sponsor_emails_invite;
  "plugins/sponsor/emails/otp_sign_in": typeof plugins_sponsor_emails_otp_sign_in;
  "plugins/sponsor/emails/render": typeof plugins_sponsor_emails_render;
  "plugins/sponsor/emails/send": typeof plugins_sponsor_emails_send;
  "plugins/sponsor/emails/sendBatch": typeof plugins_sponsor_emails_sendBatch;
  "plugins/sponsor/emails/sender": typeof plugins_sponsor_emails_sender;
  "plugins/sponsor/emails/types": typeof plugins_sponsor_emails_types;
  "plugins/sponsor/http": typeof plugins_sponsor_http;
  "plugins/sponsor/impersonation": typeof plugins_sponsor_impersonation;
  "plugins/sponsor/integrations/wca/fetchDetails": typeof plugins_sponsor_integrations_wca_fetchDetails;
  "plugins/sponsor/integrations/wca/search": typeof plugins_sponsor_integrations_wca_search;
  "plugins/sponsor/lib/auctionState": typeof plugins_sponsor_lib_auctionState;
  "plugins/sponsor/lib/auctionSubject": typeof plugins_sponsor_lib_auctionSubject;
  "plugins/sponsor/lib/bidPlacement": typeof plugins_sponsor_lib_bidPlacement;
  "plugins/sponsor/lib/bidding": typeof plugins_sponsor_lib_bidding;
  "plugins/sponsor/lib/competitionSnapshot": typeof plugins_sponsor_lib_competitionSnapshot;
  "plugins/sponsor/lib/competitionSponsorOverrides": typeof plugins_sponsor_lib_competitionSponsorOverrides;
  "plugins/sponsor/lib/competitionSponsorStatus": typeof plugins_sponsor_lib_competitionSponsorStatus;
  "plugins/sponsor/lib/contacts": typeof plugins_sponsor_lib_contacts;
  "plugins/sponsor/lib/currency": typeof plugins_sponsor_lib_currency;
  "plugins/sponsor/lib/lifecycle": typeof plugins_sponsor_lib_lifecycle;
  "plugins/sponsor/lib/sponsorBidStatus": typeof plugins_sponsor_lib_sponsorBidStatus;
  "plugins/sponsor/lib/sponsorOwnedCompetitions": typeof plugins_sponsor_lib_sponsorOwnedCompetitions;
  "plugins/sponsor/lib/sponsorshipLifecycle": typeof plugins_sponsor_lib_sponsorshipLifecycle;
  "plugins/sponsor/lib/types": typeof plugins_sponsor_lib_types;
  "plugins/sponsor/lib/validators": typeof plugins_sponsor_lib_validators;
  "plugins/sponsor/lib/visibility": typeof plugins_sponsor_lib_visibility;
  "plugins/sponsor/lib/wcaIntegration": typeof plugins_sponsor_lib_wcaIntegration;
  "plugins/sponsor/plugin": typeof plugins_sponsor_plugin;
  "plugins/sponsor/portal/auctions": typeof plugins_sponsor_portal_auctions;
  "plugins/sponsor/portal/auth": typeof plugins_sponsor_portal_auth;
  "plugins/sponsor/portal/shared": typeof plugins_sponsor_portal_shared;
  "plugins/sponsor/portal/sponsorships": typeof plugins_sponsor_portal_sponsorships;
  "plugins/sponsor/sanitize": typeof plugins_sponsor_sanitize;
  "plugins/sponsor/siteUrls": typeof plugins_sponsor_siteUrls;
  "plugins/sponsor/testing/testHelpers": typeof plugins_sponsor_testing_testHelpers;
  "plugins/sponsor/validators": typeof plugins_sponsor_validators;
  "plugins/validators": typeof plugins_validators;
  "plugins/wca/api": typeof plugins_wca_api;
  "plugins/wca/client": typeof plugins_wca_client;
  "plugins/wca/competitionLink": typeof plugins_wca_competitionLink;
  "plugins/wca/competitionOptions": typeof plugins_wca_competitionOptions;
  "plugins/wca/definition": typeof plugins_wca_definition;
  "plugins/wca/managedCompetitions": typeof plugins_wca_managedCompetitions;
  "plugins/wca/oauth": typeof plugins_wca_oauth;
  "plugins/wca/openapiClient/client/index": typeof plugins_wca_openapiClient_client_index;
  "plugins/wca/registrationsLib": typeof plugins_wca_registrationsLib;
  "plugins/wca/resources": typeof plugins_wca_resources;
  "plugins/wca/scheduleTransferCore": typeof plugins_wca_scheduleTransferCore;
  "plugins/wca/twoFactor": typeof plugins_wca_twoFactor;
  "plugins/wca/wcifCompetition": typeof plugins_wca_wcifCompetition;
  "projectWorkflows/constants": typeof projectWorkflows_constants;
  "projectWorkflows/mutations": typeof projectWorkflows_mutations;
  "projectWorkflows/queries": typeof projectWorkflows_queries;
  "projectWorkflows/registry": typeof projectWorkflows_registry;
  "projectWorkflows/runner": typeof projectWorkflows_runner;
  "projectWorkflows/runnerQueries": typeof projectWorkflows_runnerQueries;
  "projectWorkflows/types": typeof projectWorkflows_types;
  "projectWorkflows/validators": typeof projectWorkflows_validators;
  "projects/access": typeof projects_access;
  "projects/model": typeof projects_model;
  "projects/mutations": typeof projects_mutations;
  "projects/queries": typeof projects_queries;
  "projects/statuses": typeof projects_statuses;
  "projects/validators": typeof projects_validators;
  reactions: typeof reactions;
  "refunds/actions": typeof refunds_actions;
  "refunds/api": typeof refunds_api;
  "refunds/logic": typeof refunds_logic;
  "refunds/validators": typeof refunds_validators;
  "seed/model": typeof seed_model;
  "seed/mutations": typeof seed_mutations;
  sendEmails: typeof sendEmails;
  "subscriptions/index": typeof subscriptions_index;
  "subscriptions/validators": typeof subscriptions_validators;
  "tasks/access": typeof tasks_access;
  "tasks/assignees": typeof tasks_assignees;
  "tasks/blockers/counts": typeof tasks_blockers_counts;
  "tasks/blockers/dependency": typeof tasks_blockers_dependency;
  "tasks/blockers/loader": typeof tasks_blockers_loader;
  "tasks/blockers/mutations": typeof tasks_blockers_mutations;
  "tasks/blockers/queries": typeof tasks_blockers_queries;
  "tasks/blockers/root": typeof tasks_blockers_root;
  "tasks/blockers/validators": typeof tasks_blockers_validators;
  "tasks/board": typeof tasks_board;
  "tasks/filterChips": typeof tasks_filterChips;
  "tasks/flowView": typeof tasks_flowView;
  "tasks/hierarchy": typeof tasks_hierarchy;
  "tasks/inlineRow": typeof tasks_inlineRow;
  "tasks/kind": typeof tasks_kind;
  "tasks/labels/constants": typeof tasks_labels_constants;
  "tasks/labels/model": typeof tasks_labels_model;
  "tasks/labels/mutations": typeof tasks_labels_mutations;
  "tasks/labels/queries": typeof tasks_labels_queries;
  "tasks/labels/validators": typeof tasks_labels_validators;
  "tasks/mutations": typeof tasks_mutations;
  "tasks/overdue": typeof tasks_overdue;
  "tasks/queries": typeof tasks_queries;
  "tasks/reviews/mutations": typeof tasks_reviews_mutations;
  "tasks/reviews/preview": typeof tasks_reviews_preview;
  "tasks/reviews/queries": typeof tasks_reviews_queries;
  "tasks/reviews/reviewState": typeof tasks_reviews_reviewState;
  "tasks/reviews/validators": typeof tasks_reviews_validators;
  "tasks/status/recompute": typeof tasks_status_recompute;
  "tasks/status/resolver": typeof tasks_status_resolver;
  "tasks/status/rules": typeof tasks_status_rules;
  "tasks/status/validators": typeof tasks_status_validators;
  "tasks/subtaskView": typeof tasks_subtaskView;
  "tasks/validators": typeof tasks_validators;
  "tasks/view": typeof tasks_view;
  "tasks/watchers": typeof tasks_watchers;
  "teams/discordChannels": typeof teams_discordChannels;
  "teams/model": typeof teams_model;
  "teams/mutations": typeof teams_mutations;
  "teams/queries": typeof teams_queries;
  "teams/validators": typeof teams_validators;
  "templates/mutations": typeof templates_mutations;
  "templates/queries": typeof templates_queries;
  "templates/registry": typeof templates_registry;
  "templates/resolver": typeof templates_resolver;
  "templates/validators": typeof templates_validators;
  testHelpers: typeof testHelpers;
  "testing/discordNotificationTestEnv": typeof testing_discordNotificationTestEnv;
  tokens: typeof tokens;
  "updates/model": typeof updates_model;
  "updates/mutations": typeof updates_mutations;
  "updates/queries": typeof updates_queries;
  "updates/validators": typeof updates_validators;
  urls: typeof urls;
  "users/adminModel": typeof users_adminModel;
  "users/avatar": typeof users_avatar;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/validators": typeof users_validators;
  utils: typeof utils;
  "views/mutations": typeof views_mutations;
  "views/queries": typeof views_queries;
  "views/validators": typeof views_validators;
  "wcaLogin/internal": typeof wcaLogin_internal;
  "wcaLogin/queries": typeof wcaLogin_queries;
  "wcaLogin/wcaLogin": typeof wcaLogin_wcaLogin;
  "wcaLogin/wcaLoginPaths": typeof wcaLogin_wcaLoginPaths;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  reactions: import("@convex/reactions/_generated/component.js").ComponentApi<"reactions">;
  comments: import("@hamzasaleemorg/convex-comments/_generated/component.js").ComponentApi<"comments">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  sponsorAuth: import("@/convex/plugins/sponsor/auth/component/sponsorAuth/_generated/component.js").ComponentApi<"sponsorAuth">;
};
