// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://www.worldcubeassociation.org/api"
    | "http://localhost:3000/api"
    | (string & {})
}

export type RegistrationDataV2 = {
  id: number
  registrant_id: number
  user_id: number
  guests?: number
  user: {
    id: number
    name: string
    gender: string
    country_iso2: string
    wca_id: string
  }
  competing: {
    event_ids: Array<string>
    registration_status?: string
    registered_on?: string
    comment?: string
    admin_comment?: string
  }
  payment?: {
    has_paid?: boolean
    payment_status?: string
    paid_amount_iso?: number
    currency_code?: string
    updated_at?: string
  }
}

export type BaseRegistrationConfig = {
  key: string
  isEditable: boolean
  parameters?: {
    [key: string]: unknown
  }
}

export type RequirementsStepConfig = BaseRegistrationConfig

export type WcifAttemptResult = number

export type WcifQualificationAttemptResult = {
  whenDate: string
  type: string
  resultType: "single" | "average"
  level: WcifAttemptResult
}

export type WcifRanking = number

export type WcifQualificationRanking = {
  whenDate: string
  type: string
  resultType: "single" | "average"
  level: WcifRanking
}

export type WcifQualificationAnyResult = {
  whenDate: string
  type: string
  resultType: "single" | "average"
}

export type WcifQualification =
  | ({
      type: "attemptResult"
    } & WcifQualificationAttemptResult)
  | ({
      type: "ranking"
    } & WcifQualificationRanking)
  | ({
      type: "anyResult"
    } & WcifQualificationAnyResult)

export type WcifPersonalBest = {
  eventId: string
  best: WcifAttemptResult
  worldRanking: number
  continentalRanking: number
  nationalRanking: number
  type: "single" | "average"
}

export type CompetingStepConfig = BaseRegistrationConfig & {
  parameters: {
    events_per_registration_limit?: number
    allow_registration_edits: boolean
    guest_entry_status: "unclear" | "free" | "restricted"
    guests_per_registration_limit?: number
    guests_enabled: boolean
    "uses_qualification?": boolean
    allow_registration_without_qualification: boolean
    force_comment_in_registration: boolean
    qualification_wcif: {
      [key: string]: WcifQualification
    }
    event_ids: Array<string>
    preferredEvents: Array<string>
    personalRecords: {
      single: Array<WcifPersonalBest>
      average: Array<WcifPersonalBest>
    }
  }
}

export type PaymentStepConfig = BaseRegistrationConfig & {
  parameters: {
    stripePublishableKey: string
    connectedAccountId: string
  }
}

export type ApprovalStepConfig = BaseRegistrationConfig & {
  parameters: {
    "auto_accept_enabled?": boolean
    auto_accept_preference?: "disabled" | "bulk" | "live"
  }
}

export type RegistrationConfig =
  | ({
      key: "requirements"
    } & RequirementsStepConfig)
  | ({
      key: "competing"
    } & CompetingStepConfig)
  | ({
      key: "payment"
    } & PaymentStepConfig)
  | ({
      key: "approval"
    } & ApprovalStepConfig)

export type WcifTimeLimit = {
  centiseconds: number
  cumulativeRoundIds: Array<string>
}

export type WcifCutoff = {
  numberOfAttempts: number
  attemptResult: WcifAttemptResult
}

export type WcifAdvancementConditionRanking = {
  type: string
  level: WcifRanking
}

export type WcifPercent = number

export type WcifAdvancementConditionPercent = {
  type: string
  level: WcifPercent
}

export type WcifAdvancementConditionAttemptResult = {
  type: string
  level: WcifAttemptResult
}

export type WcifAdvancementCondition =
  | ({
      type: "ranking"
    } & WcifAdvancementConditionRanking)
  | ({
      type: "percent"
    } & WcifAdvancementConditionPercent)
  | ({
      type: "attemptResult"
    } & WcifAdvancementConditionAttemptResult)

export type WcifAttempt = {
  result: WcifAttemptResult
  reconstruction?: string
}

export type WcifResult = {
  personId: number
  ranking?: number
  attempts: Array<WcifAttempt>
  best: WcifAttemptResult
  average: WcifAttemptResult
}

export type WcifScramble = string

export type WcifScrambleSet = {
  id: number
  scrambles: Array<WcifScramble>
  extraScrambles: Array<WcifScramble>
}

export type WcifRound = {
  id: string
  format: "1" | "2" | "3" | "5" | "a" | "m"
  timeLimit?: WcifTimeLimit
  cutoff?: WcifCutoff
  advancementCondition?: WcifAdvancementCondition
  results: Array<WcifResult>
  scrambleSetCount: number
  scrambleSets: Array<WcifScrambleSet>
  extensions: Array<unknown>
}

export type BaseAdminRound = WcifRound & {
  state: string
}

export type OpenRound = BaseAdminRound & {
  total_competitors: number
  competitors_live_results_entered: number
}

export type LockedRound = BaseAdminRound & {
  total_competitors: number
}

export type PendingRound = BaseAdminRound

export type ReadyRound = BaseAdminRound

export type LiveRoundAdmin =
  | ({
      state: "open"
    } & OpenRound)
  | ({
      state: "locked"
    } & LockedRound)
  | ({
      state: "pending"
    } & PendingRound)
  | ({
      state: "ready"
    } & ReadyRound)

export type LiveAttempt = {
  value: number
  attempt_number: number
}

export type LiveResult = {
  registration_id: number
  round_id: number
  global_pos: number
  local_pos: number
  best: number
  average: number
  single_record_tag: string
  average_record_tag: string
  advancing: boolean
  advancing_questionable: boolean
  event_id: string
  attempts: Array<LiveAttempt>
}

export type LiveCompetitor = {
  id: number
  registrant_id: number
  user_id: number
  name: string
  country_iso2: string
}

export type LiveRound = WcifRound & {
  results: Array<LiveResult>
  competitors: Array<LiveCompetitor>
  round_id: number
  state_hash: string
}

export type UserAvatar = {
  url: string
  thumb_url?: string
  is_default: boolean
}

export type WcifRegistration = {
  wcaRegistrationId: number
  eventIds: Array<string>
  status: string
  isCompeting: boolean
}

export type WcifAssignment = {
  activityId: number
  stationNumber: number
  assignmentCode: string
}

export type WcifPerson = {
  registrantId: number
  name: string
  wcaUserId: number
  countryIso2: string
  gender: string
  birthdate?: string
  email?: string
  avatar?: UserAvatar
  roles: Array<"delegate" | "trainee-delegate" | "organizer">
  registration?: WcifRegistration
  assignments: Array<WcifAssignment>
  personalBests: Array<WcifPersonalBest>
  extensions: Array<unknown>
}

export type LivePerson = WcifPerson & {
  results: Array<LiveResult>
}

export type TeamMembership = {
  id: number
  friendly_id: string
  leader: boolean
  senior_member: boolean
  name?: string
  wca_id?: string
  avatar?: UserAvatar
}

export type Person = {
  id: number
  name: string
  gender?: string
  wca_id: string
  country_iso2: string
  delegate_status: string
  teams: Array<TeamMembership>
  url: string
  avatar: UserAvatar
}

export type SearchResultCompetition = {
  id?: string
  name?: string
  city?: string
  country_iso2?: string
  start_date?: string
  end_date?: string
  class?: string
}

export type SearchResultUser = {
  id?: number
  name?: string
  wca_id?: string
  class?: string
}

export type SearchResultRegulation = {
  id?: string
  content?: string
  class?: string
}

export type SearchResultIncident = {
  id?: number
  title?: string
  class?: string
}

export type SearchResultPost = {
  id?: number
  title?: string
  class?: string
}

export type SearchResultPerson = {
  id?: string
  name?: string
  wca_id?: string
  class?: string
}

export type Organizer = Person & {
  delegate_status?: string
  email?: string
  avatar?: UserAvatar
}

export type CompetitionInfo = {
  id: string
  name: string
  information: string
  venue: string
  contact: string
  registration_open: string
  registration_close: string
  use_wca_registration: boolean
  guests_enabled: boolean
  announced_at: string
  base_entry_fee_lowest_denomination: number
  currency_code: string
  start_date: string
  end_date: string
  enable_donations: boolean
  competitor_limit: number
  extra_registration_requirements?: string
  on_the_spot_registration: boolean
  refund_policy_percent: number
  refund_policy_limit_date: string
  guests_entry_fee_lowest_denomination: number
  qualification_results: boolean
  event_restrictions: boolean
  cancelled_at?: string | null
  waiting_list_deadline_date: string
  event_change_deadline_date: string
  competitor_can_cancel: string
  url: string
  website: string
  city: string
  venue_address: string
  venue_details?: string
  latitude_degrees: number
  longitude_degrees: number
  country_iso2: string
  event_ids: Array<string>
  main_event_id: string
  number_of_bookmarks: number
  "uses_qualification?": boolean
  "registration_full?": boolean
  "registration_full_and_accepted?": boolean
  tab_names: Array<string>
  delegates: Array<Person>
  organizers: Array<Organizer>
}

export type CompetitionPermissions = Array<string> | "*"

export type UserPermissions = {
  can_attend_competitions: {
    scope: CompetitionPermissions
    until?: string | null
  }
  can_organize_competitions: {
    scope: CompetitionPermissions
  }
  can_administer_competitions: {
    scope: CompetitionPermissions
  }
  can_view_delegate_admin_page: {
    scope: CompetitionPermissions
  }
  can_view_delegate_report: {
    scope: CompetitionPermissions
  }
  can_edit_delegate_report: {
    scope: CompetitionPermissions
  }
  can_create_groups: {
    scope: Array<string>
  }
  can_read_groups_current: {
    scope: Array<string>
  }
  can_read_groups_past: {
    scope: Array<string>
  }
  can_edit_groups: {
    scope: Array<string>
  }
  can_access_panels: {
    scope: Array<string>
  }
  can_request_to_edit_others_profile: {
    scope: Array<string> | "*"
  }
}

export type Rank = {
  id: number
  person_id: string
  event_id: string
  best: number
  world_rank: number
  continent_rank: number
  country_rank: number
}

export type Medals = {
  gold: number
  silver: number
  bronze: number
  total: number
}

export type Records = {
  national: number
  continental: number
  world: number
  total: number
}

export type SingleAndAverageRank = {
  average: Rank
  single: Rank
}

export type PersonInfo = {
  person: Person
  previous_persons?: Array<{
    [key: string]: unknown
  }>
  ranks_single?: Array<Rank>
  ranks_average?: Array<Rank>
  medals: Medals
  records: Records
  personal_records: {
    [key: string]: SingleAndAverageRank
  }
  championship_podiums: {
    world?: Array<{
      [key: string]: unknown
    }>
    continental?: Array<{
      [key: string]: unknown
    }>
    greater_china?: Array<{
      [key: string]: unknown
    }>
    national?: Array<{
      [key: string]: unknown
    }>
  }
  competition_count: number
  total_solves: number
}

export type Result = {
  id: number
  pos: number
  best: number
  average: number
  name: string
  country_iso2: string
  competition_id: string
  event_id: string
  round_type_id: string
  format_id: string
  wca_id: string
  attempts: Array<number>
  best_index: number
  worst_index: number
  regional_single_record: string | null
  regional_average_record: string | null
}

export type Results = Array<Result>

export type Competitions = Array<CompetitionInfo>

export type UserGroup = {
  id: number
  name: string
  group_type: string
  parent_group_id?: number | null
  is_active: boolean
  is_hidden: boolean
  metadata_id?: number | null
  metadata_type?: string | null
  created_at: string
  updated_at: string
  lead_user?: Person
  metadata?: {
    id?: number
    status?: string
    created_at?: string
    updated_at?: string
    email?: string
    preferred_contact_mode?: string
    friendly_id?: string
  }
}

export type UserRole = {
  id: number
  start_date: string
  end_date: string | null
  group: UserGroup
  user: Person
  metadata: {
    id?: number
    status?: string
    created_at?: string
    updated_at?: string
    email?: string
  }
  class?: string
}

export type Country = {
  id: string
  name: string
  iso2: string
  continent_id: string
}

export type RegionalOrganization = {
  name: string
  country_iso2: string
  website: string
  logo_url?: string
}

export type WcifCountryCode = string

export type WcifActivityCode = string

export type WcifActivity = {
  id: number
  name: string
  activityCode: WcifActivityCode
  startTime: string
  endTime: string
  childActivities: Array<WcifActivity>
  scrambleSetId?: number
  extensions: Array<unknown>
}

export type WcifRoom = {
  id: number
  name: string
  color: string
  activities: Array<WcifActivity>
  extensions: Array<unknown>
}

export type WcifVenue = {
  id: number
  name: string
  latitudeMicrodegrees: number
  longitudeMicrodegrees: number
  countryIso2: WcifCountryCode
  timezone: string
  rooms: Array<WcifRoom>
  extensions: Array<unknown>
}

export type WcifSchedule = {
  startDate: string
  numberOfDays: number
  venues: Array<WcifVenue>
}

export type ExtendedResult = {
  type?: string
  id: number
  pos: number
  person_id: string
  person_name: string
  country_id: string
  competition_country_id: string
  competition_id: string
  competition_name: string
  event_id: string
  round_type_id: string
  round_id: string | null
  format_id: string
  value1: number
  value2: number
  value3: number
  value4: number
  value5: number
  best: number
  average: number
  regional_single_record: string | null
  regional_average_record: string | null
  updated_at: string
  start_date: string
  value: number
}

export type Record = {
  type?: string
  id: number
  pos: number
  person_id: string
  person_name: string
  country_id: string
  competition_country_id: string
  competition_id: string
  competition_name: string
  event_id: string
  round_type_id: string
  round_id: string | null
  format_id: string
  value1: number
  value2: number
  value3: number
  value4: number
  value5: number
  best: number
  average: number
  regional_single_record: string | null
  regional_average_record: string | null
  updated_at: string
  start_date: string
  value: number
}

export type RecordByEvent = {
  [key: string]: Array<Record>
}

export type ExportInfo = {
  export_date: string
  sql_url: string
  sql_filesize_bytes: number
  tsv_url: string
  tsv_filesize_bytes: number
  readme: string
  developer_url?: string
}

export type CompetitionIndex = {
  id: string
  name: string
  short_display_name: string
  start_date: string
  end_date: string
  registration_open: string
  registration_close: string
  announced_at: string
  country_iso2: string
  city: string
  venue: string
  latitude_degrees: number
  longitude_degrees: number
  event_ids: Array<string>
  main_event_id: string
  competitor_limit: number
  championship_types: Array<string>
  results_submitted_at?: string
  results_posted_at?: string
  report_posted_at?: string
  report_posted_by_user?: number
  delegates?: Array<{
    id: number
    name: string
    avatar: UserAvatar
  }>
}

export type MyCompetition = {
  id: string
  name: string
  website: string
  start_date: string
  end_date: string
  registration_open: string
  url: string
  city: string
  country_iso2: string
  "results_posted?": boolean
  "report_posted?": boolean
  "visible?": boolean
  "confirmed?": boolean
  "cancelled?": boolean
  short_display_name: string
  championships: Array<string>
  registration_status?: string
}

export type CompetingStatus =
  | "pending"
  | "accepted"
  | "cancelled"
  | "rejected"
  | "waiting_list"

export type General404 = {
  error: string
  data: {
    model: string
    id: string
  }
}

export type Competition404 = General404 & {
  data?: {
    model: "Competition"
    id: string
  }
}

export type WcifEvent = {
  id: string
  rounds: Array<WcifRound>
  competitorLimit?: number
  qualification?: WcifQualification
  extensions: Array<unknown>
}

export type Tabs = {
  id: string
  competition_id: string
  name: string
  content: string
  display_order: number
}

export type RegistrationData = {
  id: number
  competition_id: string
  user_id: number
  event_ids: Array<string>
}

export type Scramble = {
  id: number
  competition_id: string
  event_id: string
  round_type_id: string
  round_id: number
  group_id: string
  is_extra: string
  scramble_num: number
  scramble: string
}

export type PsychSheet = {
  sort_by: string
  sort_by_second: string
  sorted_rankings: Array<{
    name: string
    user_id: number
    wca_id: string
    country_iso2: string
    average_best: number
    average_rank: number
    single_best: number
    single_rank: number
    tied_previous: boolean
    pos: number
  }>
}

export type Translation = {
  version: string
  language: string
  language_english: string
  url: string
}

export type RegulationsTranslations = {
  current: Array<Translation>
  outdated: Array<Translation>
}

export type Incident = {
  id: string
  title: string
  private_description?: string
  public_summary: string
  created_at: string
  updated_at: string
  resolved_at: string
  digest_worthy: boolean
  digest_sent_at?: string
  url: string
  tags: Array<{
    name: string
    id?: number
    url: string
    content_html: string
  }>
  competitions: Array<{
    id: string
    name: string
    comments?: string
  }>
}

export type CompetitionRegistrationsV2Data = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations"
}

export type CompetitionRegistrationsV2Responses = {
  /**
   * Successful response
   */
  200: Array<RegistrationDataV2>
}

export type CompetitionRegistrationsV2Response =
  CompetitionRegistrationsV2Responses[keyof CompetitionRegistrationsV2Responses]

export type LiveByRoundData = {
  body?: never
  path: {
    competitionId: string
    roundId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}"
}

export type LiveByRoundResponses = {
  /**
   * Returns results
   */
  200: LiveRound
}

export type LiveByRoundResponse =
  LiveByRoundResponses[keyof LiveByRoundResponses]

export type LivePodiumsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/podiums"
}

export type LivePodiumsResponses = {
  /**
   * Returns podiums with round information
   */
  200: Array<LiveRound>
}

export type LivePodiumsResponse =
  LivePodiumsResponses[keyof LivePodiumsResponses]

export type LiveByPersonData = {
  body?: never
  path: {
    competitionId: string
    registrationId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/registrations/{registrationId}"
}

export type LiveByPersonResponses = {
  /**
   * Returns a person and their results
   */
  200: LivePerson
}

export type LiveByPersonResponse =
  LiveByPersonResponses[keyof LiveByPersonResponses]

export type HealthcheckData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/healthcheck"
}

export type HealthcheckResponses = {
  /**
   * Successful health check
   */
  200: {
    status?: string
    api_instance?: boolean
  }
}

export type HealthcheckResponse =
  HealthcheckResponses[keyof HealthcheckResponses]

export type GetScrambleProgramData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/scramble-program"
}

export type GetScrambleProgramResponses = {
  /**
   * Scramble program information
   */
  200: {
    current?: {
      name?: string
      information?: string
      download?: string
    }
    allowed?: Array<string>
    publicKeyBytes?: string | null
    history?: Array<string>
  }
}

export type GetScrambleProgramResponse =
  GetScrambleProgramResponses[keyof GetScrambleProgramResponses]

export type OmniSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search"
}

export type OmniSearchErrors = {
  /**
   * No query specified
   */
  400: {
    error?: string
  }
}

export type OmniSearchError = OmniSearchErrors[keyof OmniSearchErrors]

export type OmniSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<
      | SearchResultCompetition
      | SearchResultUser
      | SearchResultRegulation
      | SearchResultIncident
    >
  }
}

export type OmniSearchResponse = OmniSearchResponses[keyof OmniSearchResponses]

export type PostsSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search/posts"
}

export type PostsSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultPost>
  }
}

export type PostsSearchResponse =
  PostsSearchResponses[keyof PostsSearchResponses]

export type CompetitionsSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search/competitions"
}

export type CompetitionsSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultCompetition>
  }
}

export type CompetitionsSearchResponse =
  CompetitionsSearchResponses[keyof CompetitionsSearchResponses]

export type UsersSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search/users"
}

export type UsersSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultUser>
  }
}

export type UsersSearchResponse =
  UsersSearchResponses[keyof UsersSearchResponses]

export type PersonsSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
    /**
     * Include persons table data
     */
    persons_table?: boolean
  }
  url: "/v0/search/persons"
}

export type PersonsSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultPerson>
  }
}

export type PersonsSearchResponse =
  PersonsSearchResponses[keyof PersonsSearchResponses]

export type RegulationsSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search/regulations"
}

export type RegulationsSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultRegulation>
  }
}

export type RegulationsSearchResponse =
  RegulationsSearchResponses[keyof RegulationsSearchResponses]

export type IncidentsSearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Search query string
     */
    q: string
  }
  url: "/v0/search/incidents"
}

export type IncidentsSearchResponses = {
  /**
   * Search results
   */
  200: {
    result?: Array<SearchResultIncident>
  }
}

export type IncidentsSearchResponse =
  IncidentsSearchResponses[keyof IncidentsSearchResponses]

export type GetUsersByIdsData = {
  body?: never
  path?: never
  query: {
    /**
     * Comma-separated list of user IDs
     */
    ids: Array<number>
  }
  url: "/v0/users"
}

export type GetUsersByIdsResponses = {
  /**
   * List of users
   */
  200: {
    users?: Array<{
      id?: number
      wca_id?: string
      name?: string
      gender?: string
      country_iso2?: string
      country?: {
        [key: string]: unknown
      }
    }>
  }
}

export type GetUsersByIdsResponse =
  GetUsersByIdsResponses[keyof GetUsersByIdsResponses]

export type GetUsersByIdsPostData = {
  body?: {
    ids: Array<number>
  }
  path?: never
  query?: never
  url: "/v0/users"
}

export type GetUsersByIdsPostResponses = {
  /**
   * List of users
   */
  200: {
    users?: Array<{
      id?: number
      wca_id?: string
      name?: string
      gender?: string
      country_iso2?: string
      country?: {
        [key: string]: unknown
      }
    }>
  }
}

export type GetUsersByIdsPostResponse =
  GetUsersByIdsPostResponses[keyof GetUsersByIdsPostResponses]

export type GetCurrentUserData = {
  body?: never
  path?: never
  query?: {
    upcoming_competitions?: boolean
    ongoing_competitions?: boolean
  }
  url: "/v0/users/me"
}

export type GetCurrentUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown
}

export type GetCurrentUserResponses = {
  /**
   * Current user information
   */
  200: {
    user?: Person
    upcoming_competitions?: Array<CompetitionInfo>
    ongoing_competitions?: Array<CompetitionInfo>
    rankings?: {
      single?: Array<{
        [key: string]: unknown
      }>
      average?: Array<{
        [key: string]: unknown
      }>
    }
  }
}

export type GetCurrentUserResponse =
  GetCurrentUserResponses[keyof GetCurrentUserResponses]

export type GetUserByIdentifierData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/v0/users/{id}"
}

export type GetUserByIdentifierErrors = {
  /**
   * User not found
   */
  404: {
    user?: {
      [key: string]: unknown
    } | null
  }
}

export type GetUserByIdentifierError =
  GetUserByIdentifierErrors[keyof GetUserByIdentifierErrors]

export type GetUserByIdentifierResponses = {
  /**
   * User information
   */
  200: {
    user?: Person
  }
}

export type GetUserByIdentifierResponse =
  GetUserByIdentifierResponses[keyof GetUserByIdentifierResponses]

export type GetDelegatesData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/delegates"
}

export type GetDelegatesResponses = {
  /**
   * List of delegates
   */
  200: Array<Person>
}

export type GetDelegatesResponse =
  GetDelegatesResponses[keyof GetDelegatesResponses]

export type GetDelegatesSearchIndexData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/delegates/search-index"
}

export type GetDelegatesSearchIndexResponses = {
  /**
   * Delegate search index
   */
  200: Array<{
    id?: number
    name?: string
    wca_id?: string
    thumb_url?: string
  }>
}

export type GetDelegatesSearchIndexResponse =
  GetDelegatesSearchIndexResponses[keyof GetDelegatesSearchIndexResponses]

export type ListPersonsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Search query
     */
    q?: string
    /**
     * Comma-separated list of WCA IDs to filter by
     */
    wca_ids?: string
    page?: number
    per_page?: number
  }
  url: "/v0/persons"
}

export type ListPersonsResponses = {
  /**
   * Paginated list of persons
   */
  200: Array<PersonInfo>
}

export type ListPersonsResponse =
  ListPersonsResponses[keyof ListPersonsResponses]

export type PersonByWcaIdData = {
  body?: never
  path: {
    wca_id: string
  }
  query?: never
  url: "/v0/persons/{wca_id}"
}

export type PersonByWcaIdResponses = {
  /**
   * Successful response
   */
  200: PersonInfo
}

export type PersonByWcaIdResponse =
  PersonByWcaIdResponses[keyof PersonByWcaIdResponses]

export type PersonResultsData = {
  body?: never
  path: {
    wca_id: string
  }
  query?: {
    event_id?: string
  }
  url: "/v0/persons/{wca_id}/results"
}

export type PersonResultsResponses = {
  /**
   * Successful response
   */
  200: Results
}

export type PersonResultsResponse =
  PersonResultsResponses[keyof PersonResultsResponses]

export type PersonRecordsData = {
  body?: never
  path: {
    wca_id: string
  }
  query?: never
  url: "/v0/persons/{wca_id}/records"
}

export type PersonRecordsResponses = {
  /**
   * Successful response
   */
  200: Results
}

export type PersonRecordsResponse =
  PersonRecordsResponses[keyof PersonRecordsResponses]

export type PersonCompetitionsData = {
  body?: never
  path: {
    wca_id: string
  }
  query?: never
  url: "/v0/persons/{wca_id}/competitions"
}

export type PersonCompetitionsResponses = {
  /**
   * Successful response
   */
  200: Competitions
}

export type PersonCompetitionsResponse =
  PersonCompetitionsResponses[keyof PersonCompetitionsResponses]

export type GetPersonPersonalRecordsData = {
  body?: never
  path: {
    wca_id: string
  }
  query?: never
  url: "/v0/persons/{wca_id}/personal_records"
}

export type GetPersonPersonalRecordsResponses = {
  /**
   * Personal records
   */
  200: Array<WcifPersonalBest>
}

export type GetPersonPersonalRecordsResponse =
  GetPersonPersonalRecordsResponses[keyof GetPersonPersonalRecordsResponses]

export type GeocodeLocationData = {
  body?: never
  path?: never
  query: {
    /**
     * Location query string
     */
    q: string
  }
  url: "/v0/geocoding/search"
}

export type GeocodeLocationResponses = {
  /**
   * Google Maps Geocoding API response
   */
  200: {
    [key: string]: unknown
  }
}

export type GeocodeLocationResponse =
  GeocodeLocationResponses[keyof GeocodeLocationResponses]

export type GetTimezoneFromCoordsData = {
  body?: never
  path?: never
  query: {
    /**
     * Latitude in microdegrees
     */
    lat: number
    /**
     * Longitude in microdegrees
     */
    lng: number
  }
  url: "/v0/geocoding/time_zone"
}

export type GetTimezoneFromCoordsResponses = {
  /**
   * Timezone names for the coordinates
   */
  200: Array<string>
}

export type GetTimezoneFromCoordsResponse =
  GetTimezoneFromCoordsResponses[keyof GetTimezoneFromCoordsResponses]

export type GetCountriesData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/countries"
}

export type GetCountriesResponses = {
  /**
   * List of countries
   */
  200: Array<Country>
}

export type GetCountriesResponse =
  GetCountriesResponses[keyof GetCountriesResponses]

export type GetRecordsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/records"
}

export type GetRecordsResponses = {
  /**
   * Records by type
   */
  200: {
    world_records?: {
      [key: string]: {
        single?: number
        average?: number
      }
    }
    continental_records?: {
      [key: string]: {
        [key: string]: {
          single?: number
          average?: number
        }
      }
    }
    national_records?: {
      [key: string]: {
        [key: string]: {
          single?: number
          average?: number
        }
      }
    }
  }
}

export type GetRecordsResponse = GetRecordsResponses[keyof GetRecordsResponses]

export type KnownTimezonesData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/known-timezones"
}

export type KnownTimezonesResponses = {
  /**
   * Successful response
   */
  200: Array<string>
}

export type KnownTimezonesResponse =
  KnownTimezonesResponses[keyof KnownTimezonesResponses]

export type RegionalOrganizationsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/regional-organizations"
}

export type RegionalOrganizationsResponses = {
  /**
   * Retrieved organizations
   */
  200: Array<RegionalOrganization>
}

export type RegionalOrganizationsResponse =
  RegionalOrganizationsResponses[keyof RegionalOrganizationsResponses]

export type GetCompetitionSeriesData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/v0/competition_series/{id}"
}

export type GetCompetitionSeriesErrors = {
  /**
   * Competition series not found
   */
  404: unknown
}

export type GetCompetitionSeriesResponses = {
  /**
   * Competition series WCIF
   */
  200: {
    id?: string
    competitions?: Array<WcifSchedule>
  }
}

export type GetCompetitionSeriesResponse =
  GetCompetitionSeriesResponses[keyof GetCompetitionSeriesResponses]

export type GetRankingsData = {
  body?: never
  path: {
    type: string
    event_id: string
  }
  query?: {
    region?: string
    show?: string
    gender?: string
  }
  url: "/v0/results/rankings/{event_id}/{type}"
}

export type GetRankingsResponses = {
  /**
   * Successfully retrieved rankings
   */
  200: {
    rankings: Array<ExtendedResult>
    timestamp: string
  }
}

export type GetRankingsResponse =
  GetRankingsResponses[keyof GetRankingsResponses]

export type GetRecords2Data = {
  body?: never
  path?: never
  query?: {
    event_id?: string
    region?: string
    show?: string
    gender?: string
  }
  url: "/v0/results/records"
}

export type GetRecords2Responses = {
  /**
   * Successfully retrieved records
   */
  200: {
    records: RecordByEvent
    timestamp: string
  }
}

export type GetRecords2Response =
  GetRecords2Responses[keyof GetRecords2Responses]

export type GetRecordByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/v0/results/records/{id}"
}

export type GetRecordByIdResponses = {
  /**
   * Record details
   */
  200: Record
}

export type GetRecordByIdResponse =
  GetRecordByIdResponses[keyof GetRecordByIdResponses]

export type GetRecordHistoryData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/v0/results/records/{id}/history"
}

export type GetRecordHistoryResponses = {
  /**
   * Record history
   */
  200: Array<{
    type?: string
    result?: {
      [key: string]: unknown
    }
    value?: number
    personName?: string
    competitionId?: string
    date?: string
  }>
}

export type GetRecordHistoryResponse =
  GetRecordHistoryResponses[keyof GetRecordHistoryResponses]

export type GetUserQualificationDataData = {
  body?: never
  path: {
    user_id: number
  }
  query?: {
    /**
     * ISO 8601 date string
     */
    date?: string
  }
  url: "/v0/results/{user_id}/qualification_data"
}

export type GetUserQualificationDataErrors = {
  /**
   * Invalid date format
   */
  400: unknown
  /**
   * User not found
   */
  404: unknown
}

export type GetUserQualificationDataResponses = {
  /**
   * User qualification data
   */
  200: {
    [key: string]: unknown
  }
}

export type GetUserQualificationDataResponse =
  GetUserQualificationDataResponses[keyof GetUserQualificationDataResponses]

export type PublicExportsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/export/public"
}

export type PublicExportsResponses = {
  /**
   * Successfully retrieved exports
   */
  200: ExportInfo
}

export type PublicExportsResponse =
  PublicExportsResponses[keyof PublicExportsResponses]

export type CompetitionListData = {
  body?: never
  path?: never
  query?: {
    include_cancelled?: boolean
    continent?: string
    country_iso2?: string
    delegate?: string
    "event_ids[]"?: Array<string>
    start?: string
    end?: string
    admin_status?: string
    q?: string
    sort?: string
    ongoing_and_future?: string
  }
  url: "/v0/competition_index"
}

export type CompetitionListResponses = {
  /**
   * Successful response
   */
  200: Array<CompetitionIndex>
}

export type CompetitionListResponse =
  CompetitionListResponses[keyof CompetitionListResponses]

export type CompetitionList2Data = {
  body?: never
  path?: never
  query?: {
    include_cancelled?: boolean
    continent?: string
    country_iso2?: string
    delegate?: string
    "event_ids[]"?: Array<string>
    start?: string
    end?: string
    admin_status?: string
    q?: string
    sort?: string
    ongoing_and_future?: string
  }
  url: "/v0/competitions"
}

export type CompetitionList2Responses = {
  /**
   * Successful response
   */
  200: Array<CompetitionIndex>
}

export type CompetitionList2Response =
  CompetitionList2Responses[keyof CompetitionList2Responses]

export type GetMyCompetitionsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/competitions/mine"
}

export type GetMyCompetitionsResponses = {
  /**
   * Successful response
   */
  200: {
    past_competitions: Array<MyCompetition>
    future_competitions: Array<MyCompetition>
    bookmarked_competitions: Array<MyCompetition>
    registrations_by_competition: {
      [key: string]: CompetingStatus
    }
  }
}

export type GetMyCompetitionsResponse =
  GetMyCompetitionsResponses[keyof GetMyCompetitionsResponses]

export type CompetitionByIdData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}"
}

export type CompetitionByIdErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionByIdError =
  CompetitionByIdErrors[keyof CompetitionByIdErrors]

export type CompetitionByIdResponses = {
  /**
   * Successful response
   */
  200: CompetitionInfo
}

export type CompetitionByIdResponse =
  CompetitionByIdResponses[keyof CompetitionByIdResponses]

export type GetCompetitionWcifPublicData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/wcif/public"
}

export type GetCompetitionWcifPublicErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetCompetitionWcifPublicError =
  GetCompetitionWcifPublicErrors[keyof GetCompetitionWcifPublicErrors]

export type GetCompetitionWcifPublicResponses = {
  /**
   * Competition WCIF (public)
   */
  200: WcifSchedule
}

export type GetCompetitionWcifPublicResponse =
  GetCompetitionWcifPublicResponses[keyof GetCompetitionWcifPublicResponses]

export type CompetitionEventsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/events"
}

export type CompetitionEventsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionEventsError =
  CompetitionEventsErrors[keyof CompetitionEventsErrors]

export type CompetitionEventsResponses = {
  /**
   * Successful response
   */
  200: Array<WcifEvent>
}

export type CompetitionEventsResponse =
  CompetitionEventsResponses[keyof CompetitionEventsResponses]

export type CompetitionScheduleData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/schedule"
}

export type CompetitionScheduleErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionScheduleError =
  CompetitionScheduleErrors[keyof CompetitionScheduleErrors]

export type CompetitionScheduleResponses = {
  /**
   * Successful response
   */
  200: WcifSchedule
}

export type CompetitionScheduleResponse =
  CompetitionScheduleResponses[keyof CompetitionScheduleResponses]

export type CompetitionTabsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/tabs"
}

export type CompetitionTabsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionTabsError =
  CompetitionTabsErrors[keyof CompetitionTabsErrors]

export type CompetitionTabsResponses = {
  /**
   * Successful response
   */
  200: Array<Tabs>
}

export type CompetitionTabsResponse =
  CompetitionTabsResponses[keyof CompetitionTabsResponses]

export type CompetitionRegistrationsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/registrations"
}

export type CompetitionRegistrationsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionRegistrationsError =
  CompetitionRegistrationsErrors[keyof CompetitionRegistrationsErrors]

export type CompetitionRegistrationsResponses = {
  /**
   * Successful response
   */
  200: Array<RegistrationData>
}

export type CompetitionRegistrationsResponse =
  CompetitionRegistrationsResponses[keyof CompetitionRegistrationsResponses]

export type GetCompetitionCompetitorsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/competitors"
}

export type GetCompetitionCompetitorsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetCompetitionCompetitorsError =
  GetCompetitionCompetitorsErrors[keyof GetCompetitionCompetitorsErrors]

export type GetCompetitionCompetitorsResponses = {
  /**
   * List of competitors
   */
  200: Array<Person>
}

export type GetCompetitionCompetitorsResponse =
  GetCompetitionCompetitorsResponses[keyof GetCompetitionCompetitorsResponses]

export type GetCompetitionQualificationsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/qualifications"
}

export type GetCompetitionQualificationsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetCompetitionQualificationsError =
  GetCompetitionQualificationsErrors[keyof GetCompetitionQualificationsErrors]

export type GetCompetitionQualificationsResponses = {
  /**
   * Qualification WCIF
   */
  200: Array<WcifQualification>
}

export type GetCompetitionQualificationsResponse =
  GetCompetitionQualificationsResponses[keyof GetCompetitionQualificationsResponses]

export type CompetitionPodiumsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/podiums"
}

export type CompetitionPodiumsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type CompetitionPodiumsError =
  CompetitionPodiumsErrors[keyof CompetitionPodiumsErrors]

export type CompetitionPodiumsResponses = {
  /**
   * Successful Response
   */
  200: Array<Result>
}

export type CompetitionPodiumsResponse =
  CompetitionPodiumsResponses[keyof CompetitionPodiumsResponses]

export type ResultsByCompetitionData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/results"
}

export type ResultsByCompetitionResponses = {
  /**
   * Successful Response
   */
  200: Results
}

export type ResultsByCompetitionResponse =
  ResultsByCompetitionResponses[keyof ResultsByCompetitionResponses]

export type GetCompetitionEventResultsData = {
  body?: never
  path: {
    competitionId: string
    event_id: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/results/{event_id}"
}

export type GetCompetitionEventResultsErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetCompetitionEventResultsError =
  GetCompetitionEventResultsErrors[keyof GetCompetitionEventResultsErrors]

export type GetCompetitionEventResultsResponses = {
  /**
   * Event results by round
   */
  200: {
    id?: string
    rounds?: Array<{
      id?: number
      roundTypeId?: string
      isH2hMock?: boolean
      results?: Array<Result>
    }>
  }
}

export type GetCompetitionEventResultsResponse =
  GetCompetitionEventResultsResponses[keyof GetCompetitionEventResultsResponses]

export type GetScramblesData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/scrambles"
}

export type GetScramblesErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetScramblesError = GetScramblesErrors[keyof GetScramblesErrors]

export type GetScramblesResponses = {
  /**
   * Successful Response
   */
  200: Array<Scramble>
}

export type GetScramblesResponse =
  GetScramblesResponses[keyof GetScramblesResponses]

export type GetCompetitionEventScramblesData = {
  body?: never
  path: {
    competitionId: string
    event_id: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/scrambles/{event_id}"
}

export type GetCompetitionEventScramblesErrors = {
  /**
   * Competition not found
   */
  404: Competition404
}

export type GetCompetitionEventScramblesError =
  GetCompetitionEventScramblesErrors[keyof GetCompetitionEventScramblesErrors]

export type GetCompetitionEventScramblesResponses = {
  /**
   * Event scrambles by round
   */
  200: {
    id?: string
    rounds?: Array<{
      id?: number
      roundTypeId?: string
      scrambles?: Array<Scramble>
    }>
  }
}

export type GetCompetitionEventScramblesResponse =
  GetCompetitionEventScramblesResponses[keyof GetCompetitionEventScramblesResponses]

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdData = {
  body?: never
  path: {
    competitionId: string
    event_id: string
  }
  query?: {
    sort_by?: string
  }
  url: "/v0/competitions/{competitionId}/psych-sheet/{event_id}"
}

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses = {
  /**
   * Successful response
   */
  200: PsychSheet
}

export type GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponse =
  GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses[keyof GetV0CompetitionsByCompetitionIdPsychSheetByEventIdResponses]

export type RegulationTranslationsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/regulations/translations"
}

export type RegulationTranslationsResponses = {
  /**
   * Successful response
   */
  200: RegulationsTranslations
}

export type RegulationTranslationsResponse =
  RegulationTranslationsResponses[keyof RegulationTranslationsResponses]

export type RegulationsListData = {
  body?: never
  path?: never
  query?: {
    q?: string
    tags?: string
    page?: number
    per_page?: number
  }
  url: "/v0/incidents"
}

export type RegulationsListResponses = {
  /**
   * Successful response
   */
  200: Array<Incident>
}

export type RegulationsListResponse =
  RegulationsListResponses[keyof RegulationsListResponses]

export type CreateRegistrationData = {
  body?: {
    competing?: {
      status?: string
      comment?: string
      event_ids?: Array<string>
    }
  }
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/create"
}

export type CreateRegistrationErrors = {
  /**
   * Bad request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden (registration closed, etc.)
   */
  403: unknown
}

export type CreateRegistrationResponses = {
  /**
   * Registration process started
   */
  202: {
    status?: string
    message?: string
  }
}

export type CreateRegistrationResponse =
  CreateRegistrationResponses[keyof CreateRegistrationResponses]

export type GetRegistrationByIdentifierData = {
  body?: never
  path: {
    competitionId: string
    /**
     * Registration ID or User ID
     */
    id: number
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/{id}"
}

export type GetRegistrationByIdentifierErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Registration not found
   */
  404: unknown
}

export type GetRegistrationByIdentifierResponses = {
  /**
   * Registration details
   */
  200: RegistrationDataV2
}

export type GetRegistrationByIdentifierResponse =
  GetRegistrationByIdentifierResponses[keyof GetRegistrationByIdentifierResponses]

export type UpdateRegistrationData = {
  body?: {
    competing?: {
      status?: string
      comment?: string
      event_ids?: Array<string>
    }
  }
  path: {
    id: number
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/{id}/update"
}

export type UpdateRegistrationErrors = {
  /**
   * Bad request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Registration not found
   */
  404: unknown
}

export type UpdateRegistrationResponses = {
  /**
   * Registration updated
   */
  200: {
    status?: string
    registration?: RegistrationDataV2
  }
}

export type UpdateRegistrationResponse =
  UpdateRegistrationResponses[keyof UpdateRegistrationResponses]

export type GetRegistrationHistoryData = {
  body?: never
  path: {
    id: number
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/{id}/history"
}

export type GetRegistrationHistoryErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Registration not found
   */
  404: unknown
}

export type GetRegistrationHistoryResponses = {
  /**
   * Registration history
   */
  200: Array<{
    [key: string]: unknown
  }>
}

export type GetRegistrationHistoryResponse =
  GetRegistrationHistoryResponses[keyof GetRegistrationHistoryResponses]

export type GetRegistrationPaymentsData = {
  body?: never
  path: {
    id: number
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/{id}/payments"
}

export type GetRegistrationPaymentsErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Registration not found
   */
  404: unknown
}

export type GetRegistrationPaymentsResponses = {
  /**
   * Registration payment info
   */
  200: {
    [key: string]: unknown
  }
}

export type GetRegistrationPaymentsResponse =
  GetRegistrationPaymentsResponses[keyof GetRegistrationPaymentsResponses]

export type GetPaymentTicketData = {
  body?: never
  path: {
    id: number
    competitionId: string
  }
  query?: {
    iso_donation_amount?: number
  }
  url: "/v1/competitions/{competitionId}/registrations/{id}/payment_ticket"
}

export type GetPaymentTicketErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Registration not found
   */
  404: unknown
}

export type GetPaymentTicketResponses = {
  /**
   * Payment client secret
   */
  200: {
    client_secret?: string
  }
}

export type GetPaymentTicketResponse =
  GetPaymentTicketResponses[keyof GetPaymentTicketResponses]

export type GetRegistrationsAdminData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/admin"
}

export type GetRegistrationsAdminErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Competition not found
   */
  404: unknown
}

export type GetRegistrationsAdminResponses = {
  /**
   * All registrations with admin info
   */
  200: Array<RegistrationDataV2>
}

export type GetRegistrationsAdminResponse =
  GetRegistrationsAdminResponses[keyof GetRegistrationsAdminResponses]

export type BulkAutoAcceptRegistrationsData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/bulk_auto_accept"
}

export type BulkAutoAcceptRegistrationsErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Competition not found
   */
  404: unknown
}

export type BulkAutoAcceptRegistrationsResponses = {
  /**
   * Bulk auto-accept result
   */
  200: {
    accepted_count?: number
  }
}

export type BulkAutoAcceptRegistrationsResponse =
  BulkAutoAcceptRegistrationsResponses[keyof BulkAutoAcceptRegistrationsResponses]

export type BulkUpdateRegistrationsData = {
  body?: {
    requests: Array<{
      user_id?: number
      competing?: {
        status?: string
        comment?: string
        event_ids?: Array<string>
        admin_comment?: string
      }
    }>
  }
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registrations/bulk_update"
}

export type BulkUpdateRegistrationsErrors = {
  /**
   * Bad request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Unprocessable entity
   */
  422: unknown
}

export type BulkUpdateRegistrationsResponses = {
  /**
   * Registrations updated
   */
  200: {
    status?: string
    updated_registrations?: {
      [key: string]: RegistrationDataV2
    }
  }
}

export type BulkUpdateRegistrationsResponse =
  BulkUpdateRegistrationsResponses[keyof BulkUpdateRegistrationsResponses]

export type CompetitionRegistrationConfigData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/registration_config"
}

export type CompetitionRegistrationConfigResponses = {
  /**
   * Successful response
   */
  200: Array<RegistrationConfig>
}

export type CompetitionRegistrationConfigResponse =
  CompetitionRegistrationConfigResponses[keyof CompetitionRegistrationConfigResponses]

export type LiveAdminData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds"
}

export type LiveAdminResponses = {
  /**
   * Returns Live Admin Information with Rounds
   */
  200: {
    rounds: Array<LiveRoundAdmin>
  }
}

export type LiveAdminResponse = LiveAdminResponses[keyof LiveAdminResponses]

export type ClearRoundData = {
  body?: never
  path: {
    competitionId: string
    roundId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}/clear"
}

export type ClearRoundResponses = {
  /**
   * Returns number of results clear
   */
  200: {
    status: string
    recreated_rows: number
  }
}

export type ClearRoundResponse = ClearRoundResponses[keyof ClearRoundResponses]

export type OpenRoundData = {
  body?: never
  path: {
    competitionId: string
    roundId: string
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}/open"
}

export type OpenRoundResponses = {
  /**
   * Returns number of locked an created results
   */
  200: {
    status: string
    created_rows: number
    locked_rows: number
  }
}

export type OpenRoundResponse = OpenRoundResponses[keyof OpenRoundResponses]

export type UpdateLiveResultData = {
  body?: {
    attempts: Array<{
      value?: number
      attempt_number?: number
    }>
  }
  path: {
    competitionId: string
    roundId: string
    registrationId: number
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}"
}

export type UpdateLiveResultResponses = {
  /**
   * Result queued for update
   */
  200: {
    status?: string
  }
}

export type UpdateLiveResultResponse =
  UpdateLiveResultResponses[keyof UpdateLiveResultResponses]

export type AddOrUpdateLiveResultData = {
  body?: {
    attempts: Array<{
      value?: number
      attempt_number?: number
    }>
  }
  path: {
    competitionId: string
    roundId: string
    registrationId: number
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}"
}

export type AddOrUpdateLiveResultErrors = {
  /**
   * Bad request
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
}

export type AddOrUpdateLiveResultResponses = {
  /**
   * Result queued for update
   */
  200: {
    status?: string
  }
}

export type AddOrUpdateLiveResultResponse =
  AddOrUpdateLiveResultResponses[keyof AddOrUpdateLiveResultResponses]

export type QuitCompetitorFromRoundData = {
  body?: never
  path: {
    competitionId: string
    roundId: string
    registrationId: number
  }
  query?: never
  url: "/v1/competitions/{competitionId}/live/rounds/{roundId}/{registrationId}/quit"
}

export type QuitCompetitorFromRoundErrors = {
  /**
   * Cannot quit competitor with results
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
}

export type QuitCompetitorFromRoundResponses = {
  /**
   * Competitor quit from round
   */
  200: {
    status?: string
    quit?: number
  }
}

export type QuitCompetitorFromRoundResponse =
  QuitCompetitorFromRoundResponses[keyof QuitCompetitorFromRoundResponses]

export type GetMeData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/me"
}

export type GetMeResponses = {
  /**
   * Successful response with current user info
   */
  200: {
    me?: Person
  }
}

export type GetMeResponse = GetMeResponses[keyof GetMeResponses]

export type AuthResultsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/auth/results"
}

export type AuthResultsErrors = {
  /**
   * Please log in
   */
  401: unknown
  /**
   * Cannot administer results
   */
  403: unknown
}

export type AuthResultsResponses = {
  /**
   * User can admin results
   */
  200: {
    status?: string
  }
}

export type AuthResultsResponse =
  AuthResultsResponses[keyof AuthResultsResponses]

export type GetUserPersonalRecordsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/users/me/personal_records"
}

export type GetUserPersonalRecordsErrors = {
  /**
   * Unauthorized
   */
  401: unknown
}

export type GetUserPersonalRecordsResponses = {
  /**
   * Personal records for current user
   */
  200: {
    single?: Array<WcifPersonalBest>
    average?: Array<WcifPersonalBest>
  }
}

export type GetUserPersonalRecordsResponse =
  GetUserPersonalRecordsResponses[keyof GetUserPersonalRecordsResponses]

export type GetUserPreferredEventsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/users/me/preferred_events"
}

export type GetUserPreferredEventsErrors = {
  /**
   * Unauthorized
   */
  401: unknown
}

export type GetUserPreferredEventsResponses = {
  /**
   * List of preferred event IDs
   */
  200: Array<string>
}

export type GetUserPreferredEventsResponse =
  GetUserPreferredEventsResponses[keyof GetUserPreferredEventsResponses]

export type GetUserBookmarksData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/users/me/bookmarks"
}

export type GetUserBookmarksErrors = {
  /**
   * Unauthorized
   */
  401: unknown
}

export type GetUserBookmarksResponses = {
  /**
   * List of bookmarked competition IDs
   */
  200: Array<string>
}

export type GetUserBookmarksResponse =
  GetUserBookmarksResponses[keyof GetUserBookmarksResponses]

export type UserPermissionsData = {
  body?: never
  path?: never
  query?: never
  url: "/v0/users/me/permissions"
}

export type UserPermissionsResponses = {
  /**
   * Successfully retrieved permissions
   */
  200: UserPermissions
}

export type UserPermissionsResponse =
  UserPermissionsResponses[keyof UserPermissionsResponses]

export type UserGroupsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Filter by whether the group is active
     */
    isActive?: boolean
    /**
     * Filter by whether the group is hidden
     */
    isHidden?: boolean
    /**
     * Filter by group type (e.g., "officers")
     */
    groupType?: string
    /**
     * Sort by a specific field (e.g., "start_date", "-created_at")
     */
    sort?: string
  }
  url: "/v0/user_groups"
}

export type UserGroupsResponses = {
  /**
   * A list of user groups
   */
  200: Array<UserGroup>
}

export type UserGroupsResponse = UserGroupsResponses[keyof UserGroupsResponses]

export type UserRolesData = {
  body?: never
  path?: never
  query?: {
    /**
     * Filter by whether the group is active
     */
    isActive?: boolean
    /**
     * Filter by whether the group is hidden
     */
    isGroupHidden?: boolean
    /**
     * Filter by user ID
     */
    userId?: number
    /**
     * Filter by group ID
     */
    groupId?: number
    /**
     * Filter by metadata status (e.g., "chair")
     */
    status?: string
    /**
     * Filter by group type (e.g., "officers")
     */
    groupType?: string
    /**
     * Filter by parent Group
     */
    parentGroupId?: number
    /**
     * Filter by whether the user is the lead of the group
     */
    isLead?: boolean
    /**
     * Sort by a specific field (e.g., "start_date", "-created_at")
     */
    sort?: string
    /**
     * Number of results per page
     */
    perPage?: number
  }
  url: "/v0/user_roles"
}

export type UserRolesResponses = {
  /**
   * A list of user roles
   */
  200: Array<UserRole>
}

export type UserRolesResponse = UserRolesResponses[keyof UserRolesResponses]

export type CreateUserRoleData = {
  body?: {
    userId: number
    groupId?: number
    groupType?: string
    status?: string
    location?: string
    endDate?: string
    banReason?: string
    scope?: string
  }
  path?: never
  query?: never
  url: "/v0/user_roles"
}

export type CreateUserRoleErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Invalid group type or other validation error
   */
  422: unknown
}

export type CreateUserRoleResponses = {
  /**
   * Role created
   */
  200: {
    success?: boolean
  }
}

export type CreateUserRoleResponse =
  CreateUserRoleResponses[keyof CreateUserRoleResponses]

export type DeleteUserRoleData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: "/v0/user_roles/{id}"
}

export type DeleteUserRoleErrors = {
  /**
   * Unauthorized
   */
  401: unknown
}

export type DeleteUserRoleResponses = {
  /**
   * Role deleted
   */
  200: {
    success?: boolean
  }
}

export type DeleteUserRoleResponse =
  DeleteUserRoleResponses[keyof DeleteUserRoleResponses]

export type UpdateUserRoleData = {
  body?: {
    status?: string
    groupId?: number
    location?: string
    endDate?: string
    banReason?: string
    scope?: string
  }
  path: {
    id: number
  }
  query?: never
  url: "/v0/user_roles/{id}"
}

export type UpdateUserRoleErrors = {
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Invalid parameters
   */
  422: unknown
}

export type UpdateUserRoleResponses = {
  /**
   * Role updated
   */
  200: {
    success?: boolean
  }
}

export type UpdateUserRoleResponse =
  UpdateUserRoleResponses[keyof UpdateUserRoleResponses]

export type SearchUserRolesData = {
  body?: never
  path?: never
  query: {
    query: string
    groupType:
      | "delegate_regions"
      | "delegate_probation"
      | "translators"
      | "officers"
      | "teams_committees"
      | "councils"
      | "board"
      | "banned_competitors"
  }
  url: "/v0/user_roles/search"
}

export type SearchUserRolesResponses = {
  /**
   * Matching roles
   */
  200: {
    result?: Array<UserRole>
  }
}

export type SearchUserRolesResponse =
  SearchUserRolesResponses[keyof SearchUserRolesResponses]

export type GetCompetitionWcifData = {
  body?: never
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/wcif"
}

export type GetCompetitionWcifErrors = {
  /**
   * Not authorized to manage competition
   */
  403: unknown
  /**
   * Competition not found
   */
  404: unknown
}

export type GetCompetitionWcifResponses = {
  /**
   * Competition WCIF
   */
  200: WcifSchedule
}

export type GetCompetitionWcifResponse =
  GetCompetitionWcifResponses[keyof GetCompetitionWcifResponses]

export type UpdateCompetitionWcifData = {
  body?: WcifSchedule
  path: {
    competitionId: string
  }
  query?: never
  url: "/v0/competitions/{competitionId}/wcif"
}

export type UpdateCompetitionWcifErrors = {
  /**
   * Validation error
   */
  400: {
    status?: string
    error?: string
  }
  /**
   * Not authorized
   */
  403: unknown
  /**
   * Competition not found
   */
  404: unknown
}

export type UpdateCompetitionWcifError =
  UpdateCompetitionWcifErrors[keyof UpdateCompetitionWcifErrors]

export type UpdateCompetitionWcifResponses = {
  /**
   * WCIF updated successfully
   */
  200: {
    status?: string
  }
}

export type UpdateCompetitionWcifResponse =
  UpdateCompetitionWcifResponses[keyof UpdateCompetitionWcifResponses]

export type GetRegistrationDataData = {
  body?: {
    ids: Array<string>
  }
  path?: never
  query?: never
  url: "/v0/registration-data"
}

export type GetRegistrationDataResponses = {
  /**
   * Registration data for competitions
   */
  200: Array<{
    id?: string
    registration_status?: "not_open" | "open" | "closed"
  }>
}

export type GetRegistrationDataResponse =
  GetRegistrationDataResponses[keyof GetRegistrationDataResponses]
