/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AuthWcaRouteImport } from './routes/auth/wca'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as CompetitionsIdRouteImport } from './routes/competitions/$id'
import { Route as ImpersonateUserRouteImport } from './routes/impersonate/user'
import { Route as InviteOrganiserRouteImport } from './routes/invite/organiser'
import { Route as PluginsSocialMediaRouteImport } from './routes/plugins/social-media'
import { Route as PluginsSponsorshipRouteImport } from './routes/plugins/sponsorship'
import { Route as PluginsWca2faRouteImport } from './routes/plugins/wca-2fa'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as SponsorIndexRouteImport } from './routes/sponsor/index'
import { Route as Sponsor404RouteImport } from './routes/sponsor/404'
import { Route as SponsorAuctionsRouteImport } from './routes/sponsor/auctions'
import { Route as SponsorGuideRouteImport } from './routes/sponsor/guide'
import { Route as SponsorImpersonateRouteImport } from './routes/sponsor/impersonate'
import { Route as SponsorLoginRouteImport } from './routes/sponsor/login'
import { Route as SponsorSettingsRouteImport } from './routes/sponsor/settings'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as AdminServiceAccountsCallbackRouteImport } from './routes/admin/service-accounts/callback'
import { Route as SponsorAuctionsAuctionIdRouteImport } from './routes/sponsor/auctions/$auctionId'
import { Route as PluginsSponsorshipAuctionsNewRouteImport } from './routes/plugins/sponsorship_.auctions.new'
import { Route as TeamsTeamIdProjectsIndexRouteImport } from './routes/teams/$teamId/projects/index'
import { Route as TeamsTeamIdTasksIndexRouteImport } from './routes/teams/$teamId/tasks/index'
import { Route as PluginsSponsorshipAuctionsAuctionIdEditRouteImport } from './routes/plugins/sponsorship_.auctions.$auctionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWcaRoute = AuthWcaRouteImport.update({
  id: '/auth/wca',
  path: '/auth/wca',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIdRoute = CompetitionsIdRouteImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateUserRoute = ImpersonateUserRouteImport.update({
  id: '/impersonate/user',
  path: '/impersonate/user',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteOrganiserRoute = InviteOrganiserRouteImport.update({
  id: '/invite/organiser',
  path: '/invite/organiser',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSocialMediaRoute = PluginsSocialMediaRouteImport.update({
  id: '/plugins/social-media',
  path: '/plugins/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSponsorshipRoute = PluginsSponsorshipRouteImport.update({
  id: '/plugins/sponsorship',
  path: '/plugins/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsWca2faRoute = PluginsWca2faRouteImport.update({
  id: '/plugins/wca-2fa',
  path: '/plugins/wca-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorIndexRoute = SponsorIndexRouteImport.update({
  id: '/sponsor/',
  path: '/sponsor/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sponsor404Route = Sponsor404RouteImport.update({
  id: '/sponsor/404',
  path: '/sponsor/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorAuctionsRoute = SponsorAuctionsRouteImport.update({
  id: '/sponsor/auctions',
  path: '/sponsor/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorGuideRoute = SponsorGuideRouteImport.update({
  id: '/sponsor/guide',
  path: '/sponsor/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorImpersonateRoute = SponsorImpersonateRouteImport.update({
  id: '/sponsor/impersonate',
  path: '/sponsor/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorLoginRoute = SponsorLoginRouteImport.update({
  id: '/sponsor/login',
  path: '/sponsor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorSettingsRoute = SponsorSettingsRouteImport.update({
  id: '/sponsor/settings',
  path: '/sponsor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceAccountsCallbackRoute =
  AdminServiceAccountsCallbackRouteImport.update({
    id: '/admin/service-accounts/callback',
    path: '/admin/service-accounts/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const SponsorAuctionsAuctionIdRoute =
  SponsorAuctionsAuctionIdRouteImport.update({
    id: '/$auctionId',
    path: '/$auctionId',
    getParentRoute: () => SponsorAuctionsRoute,
  } as any)
const PluginsSponsorshipAuctionsNewRoute =
  PluginsSponsorshipAuctionsNewRouteImport.update({
    id: '/plugins/sponsorship_/auctions/new',
    path: '/plugins/sponsorship/auctions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamIdProjectsIndexRoute =
  TeamsTeamIdProjectsIndexRouteImport.update({
    id: '/teams/$teamId/projects/',
    path: '/teams/$teamId/projects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamIdTasksIndexRoute = TeamsTeamIdTasksIndexRouteImport.update({
  id: '/teams/$teamId/tasks/',
  path: '/teams/$teamId/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSponsorshipAuctionsAuctionIdEditRoute =
  PluginsSponsorshipAuctionsAuctionIdEditRouteImport.update({
    id: '/plugins/sponsorship_/auctions/$auctionId/edit',
    path: '/plugins/sponsorship/auctions/$auctionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/auth/wca': typeof AuthWcaRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/impersonate/user': typeof ImpersonateUserRoute
  '/invite/organiser': typeof InviteOrganiserRoute
  '/plugins/social-media': typeof PluginsSocialMediaRoute
  '/plugins/sponsorship': typeof PluginsSponsorshipRoute
  '/plugins/wca-2fa': typeof PluginsWca2faRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sponsor/404': typeof Sponsor404Route
  '/sponsor/auctions': typeof SponsorAuctionsRouteWithChildren
  '/sponsor/guide': typeof SponsorGuideRoute
  '/sponsor/impersonate': typeof SponsorImpersonateRoute
  '/sponsor/login': typeof SponsorLoginRoute
  '/sponsor/settings': typeof SponsorSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sponsor/': typeof SponsorIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/service-accounts/callback': typeof AdminServiceAccountsCallbackRoute
  '/sponsor/auctions/$auctionId': typeof SponsorAuctionsAuctionIdRoute
  '/plugins/sponsorship/auctions/new': typeof PluginsSponsorshipAuctionsNewRoute
  '/teams/$teamId/projects/': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/tasks/': typeof TeamsTeamIdTasksIndexRoute
  '/plugins/sponsorship/auctions/$auctionId/edit': typeof PluginsSponsorshipAuctionsAuctionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/auth/wca': typeof AuthWcaRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/impersonate/user': typeof ImpersonateUserRoute
  '/invite/organiser': typeof InviteOrganiserRoute
  '/plugins/social-media': typeof PluginsSocialMediaRoute
  '/plugins/sponsorship': typeof PluginsSponsorshipRoute
  '/plugins/wca-2fa': typeof PluginsWca2faRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sponsor/404': typeof Sponsor404Route
  '/sponsor/auctions': typeof SponsorAuctionsRouteWithChildren
  '/sponsor/guide': typeof SponsorGuideRoute
  '/sponsor/impersonate': typeof SponsorImpersonateRoute
  '/sponsor/login': typeof SponsorLoginRoute
  '/sponsor/settings': typeof SponsorSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/admin': typeof AdminIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sponsor': typeof SponsorIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/admin/service-accounts/callback': typeof AdminServiceAccountsCallbackRoute
  '/sponsor/auctions/$auctionId': typeof SponsorAuctionsAuctionIdRoute
  '/plugins/sponsorship/auctions/new': typeof PluginsSponsorshipAuctionsNewRoute
  '/teams/$teamId/projects': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/tasks': typeof TeamsTeamIdTasksIndexRoute
  '/plugins/sponsorship/auctions/$auctionId/edit': typeof PluginsSponsorshipAuctionsAuctionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/auth/wca': typeof AuthWcaRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/impersonate/user': typeof ImpersonateUserRoute
  '/invite/organiser': typeof InviteOrganiserRoute
  '/plugins/social-media': typeof PluginsSocialMediaRoute
  '/plugins/sponsorship': typeof PluginsSponsorshipRoute
  '/plugins/wca-2fa': typeof PluginsWca2faRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sponsor/404': typeof Sponsor404Route
  '/sponsor/auctions': typeof SponsorAuctionsRouteWithChildren
  '/sponsor/guide': typeof SponsorGuideRoute
  '/sponsor/impersonate': typeof SponsorImpersonateRoute
  '/sponsor/login': typeof SponsorLoginRoute
  '/sponsor/settings': typeof SponsorSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sponsor/': typeof SponsorIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/admin/service-accounts/callback': typeof AdminServiceAccountsCallbackRoute
  '/sponsor/auctions/$auctionId': typeof SponsorAuctionsAuctionIdRoute
  '/plugins/sponsorship_/auctions/new': typeof PluginsSponsorshipAuctionsNewRoute
  '/teams/$teamId/projects/': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/tasks/': typeof TeamsTeamIdTasksIndexRoute
  '/plugins/sponsorship_/auctions/$auctionId/edit': typeof PluginsSponsorshipAuctionsAuctionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/events'
    | '/admin/refunds'
    | '/auth/wca'
    | '/competitions/$id'
    | '/impersonate/user'
    | '/invite/organiser'
    | '/plugins/social-media'
    | '/plugins/sponsorship'
    | '/plugins/wca-2fa'
    | '/projects/$id'
    | '/sponsor/404'
    | '/sponsor/auctions'
    | '/sponsor/guide'
    | '/sponsor/impersonate'
    | '/sponsor/login'
    | '/sponsor/settings'
    | '/tasks/$id'
    | '/admin/'
    | '/competitions/'
    | '/projects/'
    | '/sponsor/'
    | '/tasks/'
    | '/admin/service-accounts/callback'
    | '/sponsor/auctions/$auctionId'
    | '/plugins/sponsorship/auctions/new'
    | '/teams/$teamId/projects/'
    | '/teams/$teamId/tasks/'
    | '/plugins/sponsorship/auctions/$auctionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/events'
    | '/admin/refunds'
    | '/auth/wca'
    | '/competitions/$id'
    | '/impersonate/user'
    | '/invite/organiser'
    | '/plugins/social-media'
    | '/plugins/sponsorship'
    | '/plugins/wca-2fa'
    | '/projects/$id'
    | '/sponsor/404'
    | '/sponsor/auctions'
    | '/sponsor/guide'
    | '/sponsor/impersonate'
    | '/sponsor/login'
    | '/sponsor/settings'
    | '/tasks/$id'
    | '/admin'
    | '/competitions'
    | '/projects'
    | '/sponsor'
    | '/tasks'
    | '/admin/service-accounts/callback'
    | '/sponsor/auctions/$auctionId'
    | '/plugins/sponsorship/auctions/new'
    | '/teams/$teamId/projects'
    | '/teams/$teamId/tasks'
    | '/plugins/sponsorship/auctions/$auctionId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/events'
    | '/admin/refunds'
    | '/auth/wca'
    | '/competitions/$id'
    | '/impersonate/user'
    | '/invite/organiser'
    | '/plugins/social-media'
    | '/plugins/sponsorship'
    | '/plugins/wca-2fa'
    | '/projects/$id'
    | '/sponsor/404'
    | '/sponsor/auctions'
    | '/sponsor/guide'
    | '/sponsor/impersonate'
    | '/sponsor/login'
    | '/sponsor/settings'
    | '/tasks/$id'
    | '/admin/'
    | '/competitions/'
    | '/projects/'
    | '/sponsor/'
    | '/tasks/'
    | '/admin/service-accounts/callback'
    | '/sponsor/auctions/$auctionId'
    | '/plugins/sponsorship_/auctions/new'
    | '/teams/$teamId/projects/'
    | '/teams/$teamId/tasks/'
    | '/plugins/sponsorship_/auctions/$auctionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AuthWcaRoute: typeof AuthWcaRoute
  CompetitionsIdRoute: typeof CompetitionsIdRoute
  ImpersonateUserRoute: typeof ImpersonateUserRoute
  InviteOrganiserRoute: typeof InviteOrganiserRoute
  PluginsSocialMediaRoute: typeof PluginsSocialMediaRoute
  PluginsSponsorshipRoute: typeof PluginsSponsorshipRoute
  PluginsWca2faRoute: typeof PluginsWca2faRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  Sponsor404Route: typeof Sponsor404Route
  SponsorAuctionsRoute: typeof SponsorAuctionsRouteWithChildren
  SponsorGuideRoute: typeof SponsorGuideRoute
  SponsorImpersonateRoute: typeof SponsorImpersonateRoute
  SponsorLoginRoute: typeof SponsorLoginRoute
  SponsorSettingsRoute: typeof SponsorSettingsRoute
  TasksIdRoute: typeof TasksIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SponsorIndexRoute: typeof SponsorIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  AdminServiceAccountsCallbackRoute: typeof AdminServiceAccountsCallbackRoute
  PluginsSponsorshipAuctionsNewRoute: typeof PluginsSponsorshipAuctionsNewRoute
  TeamsTeamIdProjectsIndexRoute: typeof TeamsTeamIdProjectsIndexRoute
  TeamsTeamIdTasksIndexRoute: typeof TeamsTeamIdTasksIndexRoute
  PluginsSponsorshipAuctionsAuctionIdEditRoute: typeof PluginsSponsorshipAuctionsAuctionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/wca': {
      id: '/auth/wca'
      path: '/auth/wca'
      fullPath: '/auth/wca'
      preLoaderRoute: typeof AuthWcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate/user': {
      id: '/impersonate/user'
      path: '/impersonate/user'
      fullPath: '/impersonate/user'
      preLoaderRoute: typeof ImpersonateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/organiser': {
      id: '/invite/organiser'
      path: '/invite/organiser'
      fullPath: '/invite/organiser'
      preLoaderRoute: typeof InviteOrganiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/social-media': {
      id: '/plugins/social-media'
      path: '/plugins/social-media'
      fullPath: '/plugins/social-media'
      preLoaderRoute: typeof PluginsSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/sponsorship': {
      id: '/plugins/sponsorship'
      path: '/plugins/sponsorship'
      fullPath: '/plugins/sponsorship'
      preLoaderRoute: typeof PluginsSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/wca-2fa': {
      id: '/plugins/wca-2fa'
      path: '/plugins/wca-2fa'
      fullPath: '/plugins/wca-2fa'
      preLoaderRoute: typeof PluginsWca2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/': {
      id: '/sponsor/'
      path: '/sponsor'
      fullPath: '/sponsor/'
      preLoaderRoute: typeof SponsorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/404': {
      id: '/sponsor/404'
      path: '/sponsor/404'
      fullPath: '/sponsor/404'
      preLoaderRoute: typeof Sponsor404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/auctions': {
      id: '/sponsor/auctions'
      path: '/sponsor/auctions'
      fullPath: '/sponsor/auctions'
      preLoaderRoute: typeof SponsorAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/guide': {
      id: '/sponsor/guide'
      path: '/sponsor/guide'
      fullPath: '/sponsor/guide'
      preLoaderRoute: typeof SponsorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/impersonate': {
      id: '/sponsor/impersonate'
      path: '/sponsor/impersonate'
      fullPath: '/sponsor/impersonate'
      preLoaderRoute: typeof SponsorImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/login': {
      id: '/sponsor/login'
      path: '/sponsor/login'
      fullPath: '/sponsor/login'
      preLoaderRoute: typeof SponsorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/settings': {
      id: '/sponsor/settings'
      path: '/sponsor/settings'
      fullPath: '/sponsor/settings'
      preLoaderRoute: typeof SponsorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-accounts/callback': {
      id: '/admin/service-accounts/callback'
      path: '/admin/service-accounts/callback'
      fullPath: '/admin/service-accounts/callback'
      preLoaderRoute: typeof AdminServiceAccountsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/auctions/$auctionId': {
      id: '/sponsor/auctions/$auctionId'
      path: '/$auctionId'
      fullPath: '/sponsor/auctions/$auctionId'
      preLoaderRoute: typeof SponsorAuctionsAuctionIdRouteImport
      parentRoute: typeof SponsorAuctionsRoute
    }
    '/plugins/sponsorship_/auctions/new': {
      id: '/plugins/sponsorship_/auctions/new'
      path: '/plugins/sponsorship/auctions/new'
      fullPath: '/plugins/sponsorship/auctions/new'
      preLoaderRoute: typeof PluginsSponsorshipAuctionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/projects/': {
      id: '/teams/$teamId/projects/'
      path: '/teams/$teamId/projects'
      fullPath: '/teams/$teamId/projects/'
      preLoaderRoute: typeof TeamsTeamIdProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/tasks/': {
      id: '/teams/$teamId/tasks/'
      path: '/teams/$teamId/tasks'
      fullPath: '/teams/$teamId/tasks/'
      preLoaderRoute: typeof TeamsTeamIdTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/sponsorship_/auctions/$auctionId/edit': {
      id: '/plugins/sponsorship_/auctions/$auctionId/edit'
      path: '/plugins/sponsorship/auctions/$auctionId/edit'
      fullPath: '/plugins/sponsorship/auctions/$auctionId/edit'
      preLoaderRoute: typeof PluginsSponsorshipAuctionsAuctionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SponsorAuctionsRouteChildren {
  SponsorAuctionsAuctionIdRoute: typeof SponsorAuctionsAuctionIdRoute
}

const SponsorAuctionsRouteChildren: SponsorAuctionsRouteChildren = {
  SponsorAuctionsAuctionIdRoute: SponsorAuctionsAuctionIdRoute,
}

const SponsorAuctionsRouteWithChildren = SponsorAuctionsRoute._addFileChildren(
  SponsorAuctionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AuthWcaRoute: AuthWcaRoute,
  CompetitionsIdRoute: CompetitionsIdRoute,
  ImpersonateUserRoute: ImpersonateUserRoute,
  InviteOrganiserRoute: InviteOrganiserRoute,
  PluginsSocialMediaRoute: PluginsSocialMediaRoute,
  PluginsSponsorshipRoute: PluginsSponsorshipRoute,
  PluginsWca2faRoute: PluginsWca2faRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  Sponsor404Route: Sponsor404Route,
  SponsorAuctionsRoute: SponsorAuctionsRouteWithChildren,
  SponsorGuideRoute: SponsorGuideRoute,
  SponsorImpersonateRoute: SponsorImpersonateRoute,
  SponsorLoginRoute: SponsorLoginRoute,
  SponsorSettingsRoute: SponsorSettingsRoute,
  TasksIdRoute: TasksIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SponsorIndexRoute: SponsorIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  AdminServiceAccountsCallbackRoute: AdminServiceAccountsCallbackRoute,
  PluginsSponsorshipAuctionsNewRoute: PluginsSponsorshipAuctionsNewRoute,
  TeamsTeamIdProjectsIndexRoute: TeamsTeamIdProjectsIndexRoute,
  TeamsTeamIdTasksIndexRoute: TeamsTeamIdTasksIndexRoute,
  PluginsSponsorshipAuctionsAuctionIdEditRoute:
    PluginsSponsorshipAuctionsAuctionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
