/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as TasksMyRouteImport } from './routes/tasks/my'
import { Route as TasksArchivedRouteImport } from './routes/tasks/archived'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as InboxSettingsRouteImport } from './routes/inbox/settings'
import { Route as CompetitionsCalendarRouteImport } from './routes/competitions/calendar'
import { Route as CompetitionsIdRouteImport } from './routes/competitions/$id'
import { Route as AdminGodModeRouteImport } from './routes/admin/god-mode'
import { Route as AdminEmailRouteImport } from './routes/admin/email'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMyRoute = TasksMyRouteImport.update({
  id: '/tasks/my',
  path: '/tasks/my',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksArchivedRoute = TasksArchivedRouteImport.update({
  id: '/tasks/archived',
  path: '/tasks/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxSettingsRoute = InboxSettingsRouteImport.update({
  id: '/inbox/settings',
  path: '/inbox/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCalendarRoute = CompetitionsCalendarRouteImport.update({
  id: '/competitions/calendar',
  path: '/competitions/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIdRoute = CompetitionsIdRouteImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGodModeRoute = AdminGodModeRouteImport.update({
  id: '/admin/god-mode',
  path: '/admin/god-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/admin/email',
  path: '/admin/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/god-mode': typeof AdminGodModeRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions/calendar': typeof CompetitionsCalendarRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/archived': typeof TasksArchivedRoute
  '/tasks/my': typeof TasksMyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/god-mode': typeof AdminGodModeRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions/calendar': typeof CompetitionsCalendarRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/archived': typeof TasksArchivedRoute
  '/tasks/my': typeof TasksMyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/god-mode': typeof AdminGodModeRoute
  '/competitions/$id': typeof CompetitionsIdRoute
  '/competitions/calendar': typeof CompetitionsCalendarRoute
  '/inbox/settings': typeof InboxSettingsRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/archived': typeof TasksArchivedRoute
  '/tasks/my': typeof TasksMyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/admin/email'
    | '/admin/god-mode'
    | '/competitions/$id'
    | '/competitions/calendar'
    | '/inbox/settings'
    | '/tasks/$id'
    | '/tasks/archived'
    | '/tasks/my'
    | '/teams/$teamId'
    | '/competitions/'
    | '/inbox/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/admin/email'
    | '/admin/god-mode'
    | '/competitions/$id'
    | '/competitions/calendar'
    | '/inbox/settings'
    | '/tasks/$id'
    | '/tasks/archived'
    | '/tasks/my'
    | '/teams/$teamId'
    | '/competitions'
    | '/inbox'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/admin/email'
    | '/admin/god-mode'
    | '/competitions/$id'
    | '/competitions/calendar'
    | '/inbox/settings'
    | '/tasks/$id'
    | '/tasks/archived'
    | '/tasks/my'
    | '/teams/$teamId'
    | '/competitions/'
    | '/inbox/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminGodModeRoute: typeof AdminGodModeRoute
  CompetitionsIdRoute: typeof CompetitionsIdRoute
  CompetitionsCalendarRoute: typeof CompetitionsCalendarRoute
  InboxSettingsRoute: typeof InboxSettingsRoute
  TasksIdRoute: typeof TasksIdRoute
  TasksArchivedRoute: typeof TasksArchivedRoute
  TasksMyRoute: typeof TasksMyRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/my': {
      id: '/tasks/my'
      path: '/tasks/my'
      fullPath: '/tasks/my'
      preLoaderRoute: typeof TasksMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/archived': {
      id: '/tasks/archived'
      path: '/tasks/archived'
      fullPath: '/tasks/archived'
      preLoaderRoute: typeof TasksArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/settings': {
      id: '/inbox/settings'
      path: '/inbox/settings'
      fullPath: '/inbox/settings'
      preLoaderRoute: typeof InboxSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/calendar': {
      id: '/competitions/calendar'
      path: '/competitions/calendar'
      fullPath: '/competitions/calendar'
      preLoaderRoute: typeof CompetitionsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/god-mode': {
      id: '/admin/god-mode'
      path: '/admin/god-mode'
      fullPath: '/admin/god-mode'
      preLoaderRoute: typeof AdminGodModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/admin/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminGodModeRoute: AdminGodModeRoute,
  CompetitionsIdRoute: CompetitionsIdRoute,
  CompetitionsCalendarRoute: CompetitionsCalendarRoute,
  InboxSettingsRoute: InboxSettingsRoute,
  TasksIdRoute: TasksIdRoute,
  TasksArchivedRoute: TasksArchivedRoute,
  TasksMyRoute: TasksMyRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
